### ISSUE TITLE
Fix redirect link (ru docs)

### ISSUE THREAD

**Issue by 4iloveg** [phalcon/docs#1003]
If click https://phalcon.link/docs on https://phalconphp.com/ru/ you redirected to https://docs.phalconphp.com/en/latest/index.html . 
Needed https://docs.phalconphp.com/ru/latest/index.html

**Comment by niden** [comment]
That is not actually a bug, it is working as it should. 

https://phalcon.link/docs -> always goes to the English language.

We can change some of the URLs that need this to  /<language>/<url part> instead of the phalcon.link/ shortener.

Can you let me know where this is needed to get an idea?

**Comment by 4iloveg** [comment]
![image](https://user-images.githubusercontent.com/19300333/27255227-92db83ac-53a2-11e7-9ee6-4f9e594e78b0.png)
"Документация": replace https://phalcon.link/docs by https://docs.phalconphp.com/ru/latest/index.html


in https://docs.phalconphp.com/ru/latest/index.html and can on other language versions:
![image](https://user-images.githubusercontent.com/19300333/27255200-36f1b296-53a2-11e7-93ea-d94f39c2bfc6.png)
download and documentation - need to the current language prefix in link.

**Comment by ninjapanzer** [comment]
Here is what I want to do. I want to allow phalcon.link to pass through the language if present

**Comment by ninjapanzer** [comment]
@niden might want to take a look at https://github.com/phalcon/link/pull/12
