### ISSUE TITLE
Action Regex Mismatch with Docs

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#1009]
_From @aleemb on November 24, 2014 12:19_

Somewhere along the line, the regex for `:action` was updated from:

```
// http://docs.phalconphp.com/en/latest/reference/routing.html
/([a-zA-Z0-9_]+)
```

to

```
// https://github.com/phalcon/cphalcon/blob/master/ext/mvc/router/route.c#L274
/([a-zA-Z0-9_-]+)
```

I remember this wasn't always the case, but at some point the code was updated but the document didn't reflect the new changes.

_Copied from original issue: phalcon/cphalcon#3074_

**Comment by niden** [comment]
Fixed : 82ffd6ebdc72e795f032b2c3fab4643d60a28c09
