### ISSUE TITLE
The docs CSS needs a media query for different resolutions

### ISSUE THREAD

**Issue by dschissler** [phalcon/docs#1017]
The center content expands to take up the entire remaining space.  I think that it needs to be limited to something less.  I have 1920 pixels for width on my screen and its already becoming quite too stretched out and I'd hate to see it on 3k pixel width.  I think that this can be fixed without much trouble by using a media query of some type.

Also @niden great job on the new docs and I'm loving the directory structure.

**Comment by david-duncan** [comment]
Any mobile responsive to the docs would be great.

**Comment by niden** [comment]
@david-duncan We are working on it. There are some CSS issues on the desktop site also that will be resolved shortly

**Comment by david-duncan** [comment]
Awesome great work

**Comment by niden** [comment]
Initial CSS fixes have been released. A bit more work needs to be done (this week coming)
