### ISSUE TITLE
3.0 is missing redirects

### ISSUE THREAD

**Issue by david-duncan** [phalcon/docs#1019]
Most google results are broken because 3.0 has no redirect

https://docs.phalconphp.com/en/3.0.0/reference/models.html

**Comment by chenyangguang** [comment]
yes, why?

**Comment by niden** [comment]
This should be resolved very shortly. We just need to address the redirects correctly.

Thank you for your patience. If you need to access the old docs in the meantime, please visit:

https://olddocs.phalconphp.com

**Comment by sergeyklay** [comment]
Fixed. Thank you for contributing
