### ISSUE TITLE
Formatting of alert boxes covers right side menu. 

### ISSUE THREAD

**Issue by jellisii** [phalcon/docs#1043]
Can be seen on https://docs.phalconphp.com/en/3.2/db-models.  

Screenshot: 
![96d770d4b27f17fd817defaa1cf6b754c9869a4c527e08df6924c0fb25bf0a9d6ee9081ac8e5c777df03084e12f408e6972397b343f788bf](https://user-images.githubusercontent.com/1256298/27638830-2317a5c2-5c1d-11e7-9f06-5626e8c2d561.png)

This happens on both Firefox 54 and Chromium 58.0.3029.110 for Linux

**Comment by niden** [comment]
@jellisii I have noticed that also. We are waiting for a few last minute changes and we will be releasing a new layout (css changes etc.) this week that addresses this issue too.

Thanks for the heads up.

**Comment by niden** [comment]
This has been fixed
