### ISSUE TITLE
[Feature Request] Can the API index be returned?

### ISSUE THREAD

**Issue by jellisii** [phalcon/docs#1044]
On the old documentation, there was an API index:

https://olddocs.phalconphp.com/en/3.0.0/api/index.html

Can some analog of this be returned to the docs?

**Comment by niden** [comment]
@jellisii Absolutely that will come back again. The data is there, we just need to set it up. At the moment we are reorganizing the docs a bit more to help with translations and new releases. We are also waiting for a few minor fixes to our stylesheets. Once those are done we will also adddress the API index.

Thanks!

**Comment by niden** [comment]
This has been implemented. API index is under Core
