### ISSUE TITLE
Please Add all versions in 3.* series to the release notes

### ISSUE THREAD

**Issue by dschissler** [phalcon/docs#1073]
https://docs.phalconphp.com/en/3.2/release-notes

**Comment by sergeyklay** [comment]
`/<LANG>/<MAJOR>.<MINOR>/release-notes` => `<MAJOR>.<MINOR>.*` series

**Comment by dschissler** [comment]
I think that there should be a `v` directory in the root for these things.

**Comment by ninjapanzer** [comment]
Release notes now links directly to phalcon/cphalcon release notes for the given version
