### ISSUE TITLE
Missing tutorials

### ISSUE THREAD

**Issue by jaitaiwan** [phalcon/docs#1079]
I recently tried to on board a new staff member and asked them to go through the phalcon tutorials as a first step in learning the basics of phalcon. I was bemused to find out that the staff member couldn't find them.

After investigating myself I can see that the tutorials indeed appear to be lost from the docs site and cached google links seem to no longer work for 3.1.1 for instance.

Have the tutorials been moved elsewhere?

**Comment by sergeyklay** [comment]
* https://docs.phalconphp.com/en/latest/tutorial
* https://docs.phalconphp.com/en/3.1/tutorial
* https://docs.phalconphp.com/en/3.2/tutorial

Note: Actually the `/tutorial` URI will be redirected with 301 status code to the `/tutorial-base`. Anyway it is fixed.  Feel free to open new issue if the problem appears again. Thank you for contributing.
