### ISSUE TITLE
[NFR] Add phpdoc comments in C sources of available properties

### ISSUE THREAD

**Issue by Agent-J** [phalcon/docs#109]
`@property-read` if property is available through getter method
`@property-write` if property is available through setter method
`@property` if property is public or available through getter and setter methods

For example in (acl/adapter/memory.c):

``` C
/**
 * Phalcon\Acl\Adapter\Memory
 *
 * Manages ACL lists in memory
 *
 * ... description and usage examples
 *
 * @property-read Phalcon\Acl\Role[] $roles An array with every role registered in the list
 * @property-read Phalcon\Acl\Resource[] $resources An array with every resource registered in the list
 */
```

**Comment by niden** [comment]
Closed in favor of [1822]
