### ISSUE TITLE
Add vertical padding or margin to every <p> element

### ISSUE THREAD

**Issue by dschissler** [phalcon/docs#1100]
I think that the docs would look a lot better if there was about 1-2px of padding before and after ever `<p>` tag.  Possibly this could be done with `em` or `rem`, I'm not sure what is better.

**Comment by ninjapanzer** [comment]
@dschissler there are a lot of paragraph tags which lack sufficient semantics when rendered to apply a global rule for white space around them IMO. I would recommend that we offset our `<pre>` code block elements. I should give us a similar effect without making it look like we are just adding line height to each row of the docs. See the following examples which puts `margin: 1em 0 1em 0;` on `<pre>` elements.

Before:
<img width="836" alt="screen shot 2017-08-13 at 12 06 12 am" src="https://user-images.githubusercontent.com/159591/29246057-4283382e-7fbb-11e7-8a34-9efff9dc7bce.png">


After:
<img width="869" alt="screen shot 2017-08-13 at 12 05 37 am" src="https://user-images.githubusercontent.com/159591/29246055-33109ddc-7fbb-11e7-8390-5c07bf60dbca.png">

**Comment by niden** [comment]
Closing this due to the new docs layout deployed.
