### ISSUE TITLE
Micro Applications: Responses

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#1105]
I propose to rephrase this:

> A micro application can return many different types of responses. Direct output, use a template engine, calculated data, view based data, JSON etc.

Actually all this is not a _type_ of the response. It is approach, method, way, etc. but anyway not a _type_.

**Comment by sergeyklay** [comment]
Also I'm not sure about "view based data". Could we rephrase this also?

**Comment by sergeyklay** [comment]
In addition to what I said before I would like to draw your attention on our robotext:
```sh
$ grep -nr "You can\( also\)\?" en/application-micro.md | wc -l
      12
```

I do not think that the phrase "You can also" or "You can"  is so irreplaceable.

**Comment by niden** [comment]
What is wrong with view based data? It is data produced by a view. How else would you phrase the outcome of a view being processed?

Not sure what is wrong with the "you can also".

**Comment by sergeyklay** [comment]
That's why I wanted to discuss this. I'm not a native speaker and current "Micro Applications" docs seems a bit strange to me

**Comment by sergeyklay** [comment]
About "you can also": in my opinion there is more variations eg. "There is an ability ...", "Moreover (besides) ...", "The component X able to ...", "Phalcon designed for ...", "The service provides ...", "In addition to what we discussed above ...", "Amazing opportunities don't end there ... " :)

I don't know guys, in my native language there are hundreds of synonyms for "You can also".

**Comment by sergeyklay** [comment]
Actually there is no "view based data". There are Views in which data can be. But this doesn't means that the particular view is based on this data. The view based on Teamplate Engine and may use the data (or may not use the data).

**Comment by sergeyklay** [comment]
@niden I think I can trust your English :) As I said before I'm not native spiker. So you can safely close this issue if it doesn't make sense or irrelevant.

**Comment by niden** [comment]
Not a native speaker either buddy. I will work with Paul to get some "proper" english in the docs :)
