### ISSUE TITLE
The banner on the top is unnecessarily large and floaty

### ISSUE THREAD

**Issue by dschissler** [phalcon/docs#1116]
I think that its bad enough that its very difficult to buy a screen that is not 16x9 because there is so much less vertical space then there used to be so that its like permanently driving with the sun visor down.  Now with the banner on the top its like have two sun visors.  I'd really prefer if it didn't float at all.  Its enough that it just appear once at the top.  In this case its fancy CSS that is reducing the usability.  Also I would like the banner to be 5-10px smaller.  Lets get some work done.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/docs-app#32
