### ISSUE TITLE
Object instantiation missing in Validations example.

### ISSUE THREAD

**Issue by Cvetomird91** [phalcon/docs#1136]
Hello Phalcon Team,

I noticed that in the API indice the page for Phalcon\Validation\Validator\Date is lacking an instantiation of the $validator Validation object. I tested it in the 3.0.0, 3.2.0 and 3.1.0 Indice.

**Comment by Cvetomird91** [comment]
Here's a link to the page - https://olddocs.phalconphp.com/en/3.0.0/api/Phalcon_Validation_Validator_Date.html

**Comment by sergeyklay** [comment]
Thank you for the report, and for helping us make Phalcon better. We'll try to sort out asap. 

Cc: @niden

**Comment by Cvetomird91** [comment]
Thank you for the fast reply, I'm glad to assist.

**Comment by Cvetomird91** [comment]
I noticed the same in the docs for Phalcon 3.2:
https://docs.phalconphp.com/en/3.2/api/Phalcon_Validation_Validator_Date

**Comment by sergeyklay** [comment]
@ninjapanzer Could you please a look? Unfortunately I still can't find the time to check out this

**Comment by ninjapanzer** [comment]
@sergeyklay I will add it to my list. Should be able to get to it tonight

**Comment by ninjapanzer** [comment]
Here is what I am thinking...

The Validation docs https://docs.phalconphp.com/en/3.2/db-models-validation provide a full example. The API is providing a minimal view to the requirements to create said validator.

I am seeing this pattern of the bare minimum around most of the documents. I think it is worthwile to provide a `@seemore` `@link` to the full docs. Ultimately it would be nice for an API page to be a single location for this information.

**Comment by sergeyklay** [comment]
👍 for `@link` . IMO we should use only standard PHPDoc tags.

**Comment by ninjapanzer** [comment]
@sergeyklay Would you point me to where the Markdown API docs are being generated from? I only see HTML generation in Zephir.

**Comment by ninjapanzer** [comment]
Thank You!
This will be updated on the site shortly.
