### ISSUE TITLE
Typo in Phalcon\Mvc\Model\MetaData page for Phalcon 3.2

### ISSUE THREAD

**Issue by Cvetomird91** [phalcon/docs#1183]
Hello again guys,

Thank you for keeping Phalcon's documentation well-structured.

Here's a link to the page I am speaking about: https://docs.phalconphp.com/en/3.2/api/Phalcon_Mvc_Model_MetaData

The typo is in the example for the writeMetaDataIndex method. In the example a method called writeColumnMapIndex is used. I can't find such a method in this class, nor in Phalcon\Mvc\Model\MetaDataInterface.

**Comment by Cvetomird91** [comment]
I noticed the same in the documentation for 3.0.2:

https://olddocs.phalconphp.com/en/3.0.2/api/Phalcon_Mvc_Model_MetaData.html

**Comment by niden** [comment]
This has been addressed
