### ISSUE TITLE
Use of "Rainbow Tables" in Password Hashing Explanation

### ISSUE THREAD

**Issue by Ecksters** [phalcon/docs#1194]
From the [docs](https://docs.phalconphp.com/en/3.2/security):

> Storing passwords in plain text is a bad security practice. Anyone with access to the database will immediately have access to all user accounts thus being able to engage in unauthorized activities. To combat that, many applications use the familiar one way hashing methods 'md5' and 'sha1'. However, hardware evolves each day, and becomes faster, these algorithms are becoming vulnerable to brute force attacks. These attacks are also known as rainbow tables.
To solve this problem we can use hash algorithms as bcrypt. Why bcrypt? Thanks to its 'Eksblowfish' key setup algorithm we can make the password encryption as 'slow' as we want. Slow algorithms make the process to calculate the real password behind a hash extremely difficult if not impossible. This will protect your for a long time from a possible attack using rainbow tables.

Not to offend whoever wrote it, but this description is absolutely awful. Salting is what combats the use of Rainbow Tables, not bcrypt. This secton should be talking about BCrypt being used to prevent GPU hashing or FPGA usage, not Rainbow Tables, which at this point have been made nearly entirely obsolete due to the high speed of dedicated hashing hardware and widespread use of salting.

**Comment by ninjapanzer** [comment]
@Ecksters Thanks for the feedback!

**Comment by niden** [comment]
This has been addressed. Thank you @Ecksters
