### ISSUE TITLE
Missing object instantiation in Phalcon\Paginator\Factory

### ISSUE THREAD

**Issue by Cvetomird91** [phalcon/docs#1200]
Hello again,

There's a missing object instantiation in the example here for the QueryBuilder object ($builder). This may appear confusing for newcomers to Phalcon.

**Comment by ninjapanzer** [comment]
On which page are you referring?

**Comment by Cvetomird91** [comment]
I'm referring to https://docs.phalconphp.com/en/3.2/Phalcon_Paginator_Factory

**Comment by ninjapanzer** [comment]
It looks like $builder has a definition
<img width="1032" alt="screen shot 2017-08-22 at 8 00 21 am" src="https://user-images.githubusercontent.com/159591/29564612-8f755df4-8710-11e7-9e9c-2a3b49277712.png">

What I don't see is the $di setup for
```
$di->set('modelsManager', function() use ($eventsManager) {
  $modelsManager = new Phalcon\Mvc\Model\Manager();
  $modelsManager->setEventsManager($eventsManager);
  return $modelsManager;
}, true);
```
@niden I am looking at this from the following test
https://github.com/phalcon/cphalcon/blob/107b6f0197b0464d9f6b11ff390a560c000bf448/unit-tests/ModelsEventsTest.php#L55-L64
is modelManager wrapped up inside another service that is generally always available with using `FactoryDefault`?

**Comment by niden** [comment]
Adjusted documentation accordingly
