### ISSUE TITLE
Clarify entity and data from 3.2 validation

### ISSUE THREAD

**Issue by ganluo960214** [phalcon/docs#1207]
https://github.com/phalcon/docs/blame/3.2/en/validation.md#L222

 how to defined entity and data? what's the difference between entity and data? when I translate this I don't know it.

**Comment by ganluo960214** [comment]
When executing this validator Phalcon will pass data depending what it is - if it's an entity then entity will be passed, otherwise data.

**Comment by ninjapanzer** [comment]
An `entity` is usually an instantiated `model` object. I think I should probably take a stab and revising this before you try to translate it again.

It is confusing to me as well :)

**Comment by niden** [comment]
@GanLuo96214 Sorry for the late reply.

`entity` or `data` means a structure that you need to validate. If you need to validate an array such as the `$_POST` then you pass that. If you need to say validate a model (i.e. `entity`) then you pass that.

I will make a small change to clarify this.

**Comment by niden** [comment]
This has been resolved
