### ISSUE TITLE
Broken markdon in Phalcon 3.2 page for Phalcon\Validation\Validator\ExclusionIn

### ISSUE THREAD

**Issue by Cvetomird91** [phalcon/docs#1209]
Hello guys,

The syntax highlight in the first example code block here isn't rendering properly.

https://docs.phalconphp.com/en/3.2/api/Phalcon_Validation_Validator_ExclusionIn

**Comment by ninjapanzer** [comment]
Thank You!
This will be updated on the site shortly.
