### ISSUE TITLE
Reproducible Tests Doesn't Exist

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/docs#1236]
https://docs.phalconphp.com/en/3.2/reproducible-tests
<img width="923" alt="screen shot 2017-08-29 at 10 08 34 pm" src="https://user-images.githubusercontent.com/159591/29852176-a6d6038a-8d06-11e7-9190-fe3ae42f3216.png">

**Comment by niden** [comment]
Fixed. Thanks!
