### ISSUE TITLE
Generating Backtrace Doesn't Exist

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/docs#1237]
https://docs.phalconphp.com/en/3.2/generating-backtrac
<img width="923" alt="screen shot 2017-08-29 at 10 08 34 pm" src="https://user-images.githubusercontent.com/159591/29852217-df7a192e-8d06-11e7-8f67-06a497e2f8fd.png">
e

**Comment by niden** [comment]
Is this a typo on the URL you posted or a link in the app?

https://docs.phalconphp.com/en/3.2/generating-backtrac <- not working
https://docs.phalconphp.com/en/3.2/generating-backtrace <- correct

**Comment by ninjapanzer** [comment]
I will check it again later but seems to be working on my phone.

**Comment by ninjapanzer** [comment]
Was fixed by @niden thank you
