### ISSUE TITLE
Testing Guide link doesn't go anywhere

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/docs#1238]
<img width="180" alt="screen shot 2017-08-29 at 10 10 52 pm" src="https://user-images.githubusercontent.com/159591/29852246-13c70cdc-8d07-11e7-8338-2d7f3553c065.png">

Test Guide isn't a link.

**Comment by garyanewsome** [comment]
Do we want `Testing guide` to link to the `unit-testing.md`? Or is there another doc I am not seeing.

**Comment by niden** [comment]
I think that was the plan - the unit test -> testing guide. Is that an orphan? I don't remember
