### ISSUE TITLE
en/url.md line 146and line 149 need more information 

### ISSUE THREAD

**Issue by ganluo960214** [phalcon/docs#1248]
I got a problem about translate there two lines in `Producing URLs without mod_rewrite` section. I can't implement it with the doc offered code. I don't know those meaning. Could U show me the code that implement it.

<https://github.com/phalcon/docs/blame/3.2/en/url.md#L146>
<https://github.com/phalcon/docs/blame/3.2/en/url.md#L149>

**Comment by hamidrezabstn** [comment]
@GanLuo96214 

please send your code here

**Comment by ganluo960214** [comment]
Because I don't know implement it. so I ask for help.

**Comment by ganluo960214** [comment]
I can't send the code.

**Comment by niden** [comment]
@GanLuo96214 

```
// Pass the URI in $_GET['_url']
147	$url->setBaseUri('/invo/index.php?_url=/');
```

This means that we can pass the URL using the `$_GET['_url']` superglobal element. For instance when you see in the browser:

```
http://example.com/hello/world
```

the URI is `hello/world`. 

Phalcon uses a special `$_GET` variable named ``_url`. So you can either do this:

```
$_GET['_url'] = 'hello/world'
```

or

```
http://example.com/?_url=hello/world
```

So the comment means that you can pass the URI using the `$_GET['_url']` superglobal element

**Comment by niden** [comment]
With the above, since Phalcon uses the `_url` GET variable to store the URI, if you call:

```
echo $url->get('products/save');
```

is the same as:

```
/invo/index.php?_url=/products/save
```

**Comment by niden** [comment]
Closing. No additional information. Please reopen if this is still an issue.
