### ISSUE TITLE
A more clear example for Phalcon\Mvc\Model::hasOne

### ISSUE THREAD

**Issue by Cvetomird91** [phalcon/docs#1315]
Hello,

I noticed that there were no examples in the API documentation (https://docs.phalconphp.com/en/3.2/api/Phalcon_Mvc_Model) and the Phalcon Framework guide (https://docs.phalconphp.com/en/3.2/db-models-relationships) which describe relationships within more than one column between two tables. 

Here's a such example:

`$this->hasOne(['id', 'type'], 'Modules\Groups', ['group_id', 'type'], ['alias' => 'group']);
`

I think that including such an example will make the documentation more clearer for new comers and expose them to another good capability of the framework.

**Comment by Cvetomird91** [comment]
PS: I think that this might as well apply to Phalcon\Mvc\Model::hasMany

**Comment by Jurigag** [comment]
hasOne is the same thing as hasMany, just hasOne returns model instance instead of resultset. Something like this should be enough.

**Comment by niden** [comment]
Resolved
