### ISSUE TITLE
Update Old docs to point to releases instead of cphalcon head 

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/docs#1321]
Currently https://olddocs.phalconphp.com/en/2.0.0/reference/install.html
Says to use
<img width="683" alt="screen shot 2017-09-19 at 6 38 36 pm" src="https://user-images.githubusercontent.com/159591/30618757-d5e72712-9d69-11e7-8b2d-7be3a9ee0423.png">
This results in users trying to install 3.2 which is not the desired effect.

It should point them to: https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.13

Please see: https://stackoverflow.com/questions/46295654/how-to-install-specific-phalcon-framework-version-2-0/46300234?noredirect=1#comment79564363_46300234

**Comment by niden** [comment]
This has been addressed
