### ISSUE TITLE
Phalcon_Db_Profiler example

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs#1326]
Looking at the profiler I don't think the example is valid any more.

https://docs.phalconphp.com/en/latest/api/Phalcon_Db_Profiler

~~Unfortunately I was unable to exactly figure out the working otherwise I would sent a pull~~

**Comment by ninjapanzer** [comment]
Cphalcon Docblock updated: https://github.com/phalcon/cphalcon/pull/13086
