### ISSUE TITLE
No explicit documentation page Title

### ISSUE THREAD

**Issue by Nomadzy** [phalcon/docs#1328]
The HTML title of the documentation pages is "Documentation - Phalcon Framework", would be nice if this title had more info like "Validation - Documentation - Phalcon Framework", it will easy finding an open tab.
Also you are using meta tags OG and Twitter and other meta, but the informations in them are useless as there is no informations about the current page, and its bad for SEO too.

**Comment by niden** [comment]
This has been fixed

https://github.com/phalcon/docs/pull/1347
