### ISSUE TITLE
Forward olddocs to docs

### ISSUE THREAD

**Issue by quasipickle** [phalcon/docs#1333]
When I'm googling something, 100% of the official Phalcon results point to olddocs - there are no results pointing to the new docs.

I'd suggest putting a permanent redirect in that points to the new docs, so search results get updated.

**Comment by zachleigh** [comment]
This is still very much an issue. A temporary fix would be to put a link in the old docs to the new docs.

**Comment by niden** [comment]
This has been resolved.

All the links (that I could find - might have missed one or two) are now redirecting to the latest documentation from the `olddocs`. The only version unaffected is 2.0. Everything else issues a `301` and redirects.

It will take a bit for Google/Bing to catch up but so far it is working as advertised.
