### ISSUE TITLE
Typo in page for Phalcon\Mvc\Model\Resultset\Simple

### ISSUE THREAD

**Issue by Cvetomird91** [phalcon/docs#1369]
Hello Phalcon team,

There's a typo in the description for the seek method in Phalcon\Mvc\Model\Resultset\Simple.
A dot is missing before "Sets" to separate the sentences.

https://docs.phalconphp.com/en/3.2/api/Phalcon_Mvc_Model_Resultset_Simple

- [x] Update `docs:3.2` Docs (Done by @garyanewsome)
- [x] Update `cphalcon:3.2` -> `phalcon/mvc/model/resultset.zep`
- [x] Update `cphalcon:3.3` -> `phalcon/mvc/model/resultset.zep`
- [ ] (Optional) Update `cphalcon:4.0` -> `phalcon/mvc/model/resultset.zep`

**Comment by Cvetomird91** [comment]
I see that the issue has been fixed, merged and deployed. Can we close this?

**Comment by garyanewsome** [comment]
@niden @ninjapanzer what's up with this one?

**Comment by ninjapanzer** [comment]
Looks like we still need a patch back in `cphalcon`
`https://github.com/phalcon/cphalcon/blob/3.2.x/phalcon/mvc/model/resultset.zep#L211-L214`
This needs to be updated to match the new copy so it can be regenerated if needed.
Same change should be applied to `cphalcon:3.3`branch and possible `cphalcon:4.0` if this structure is the same there. Will update ticket description

**Comment by ninjapanzer** [comment]
I have resolved the doc block changes in the zep files for 3.2 and 3.3
