### ISSUE TITLE
Feature Request: Publish/generate pdf, epub and html docs.

### ISSUE THREAD

**Issue by baychae** [phalcon/docs#1386]
Feature Request: Publish/generate pdf, epub and html docs.

It would be less taxing to read documentation that can be printed or read on an e-reader. I also find hard copy easier to flick through and more immersive.

**Comment by pedroresende** [comment]
Any news about this ? It would be really usefull

**Comment by kkstun** [comment]
Any news about this ? It would be really usefull

**Comment by niden** [comment]
Closing in favor of [#1822]
