### ISSUE TITLE
Add added improvements in version 2.0.4

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/docs#1395]
The release 2.0.4 had three major improvements that are not documented and probably many developers are missing

- Typed Placeholders in the ORM
- Cast bound parameters values
- Relationships with conditionals

[more info from blog](https://blog.phalconphp.com/post/phalcon-2-0-4-released)

**Comment by niden** [comment]
Thanks @emiliodeg. I will add those sections soon.

**Comment by niden** [comment]
This has been addressed. Thanks again
