### ISSUE TITLE
[REQUEST] Phalcon configuration docs for config.json

### ISSUE THREAD

**Issue by NikoGrano** [phalcon/docs#1417]
IS there docs for `config.json`? It's used by phalcon webtools.

**Comment by NikoGrano** [comment]
Bump

**Comment by Jeckerson** [comment]
There is some docs for it in README
https://github.com/phalcon/phalcon-devtools#configuration-file

**Comment by NikoGrano** [comment]
If you see there is enough documentation and you agree with that after reading trough https://github.com/phalcon/phalcon-devtools/issues/1148, please close this issue. I'm just keeping eye on my old issues and closing them as I see it to fit best.

**Comment by NikoGrano** [comment]
I see there wasn't real feedback, so closing this as non-productive.
