### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by kaysonwu** [phalcon/docs#1436]
Phalcon is a very good framework and I love it very much. I come from China and in my country people think that learning Phalcon is very expensive. So I started to participate in the translation of the document. But I found that Crowdin has translated 100% of the documents can not be fed back to the Phalcon official website documentation, I feel this will not be able to better promote everyone's enthusiasm. Hope that the translation of the finished document can be synchronized to the official document. Thank you

**Comment by niden** [comment]
@junliuxian The translation strings appear on the site and docs once they are reviewed.

I have made you a reviewer in Crowdin so feel free to approve your translations and in the next sync your translations will appear :)

Thank you very much for your help!!
