### ISSUE TITLE
rest tutorial and closed issue cphalcon/issues/#11464

### ISSUE THREAD

**Issue by apg007** [phalcon/docs#1437]
In: 
https://docs.phalconphp.com/en/latest/tutorial-rest#models

 ...the code for "Creating a Model" (models/Robots.php) has:
use Phalcon\Mvc\Model\Validator\Uniqueness;

...which errors out with:
Fatal error: Uncaught TypeError: Argument 1 passed to Phalcon\Mvc\Model::validate() must implement interface Phalcon\ValidationInterface, instance of Phalcon\Mvc\Model\Validator\Inclusionin given in /var/www/my-rest-api/models/Robots.php on line 20

According to: 
https://github.com/phalcon/cphalcon/issues/11464

...it should be: 
use Phalcon\Validation\Validator\Uniqueness

**Comment by apg007** [comment]
...making that change corrected the error.

**Comment by apg007** [comment]
One more time... change this:
<?php

namespace Store\Toys;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Message;
use Phalcon\Mvc\Model\Validator\Uniqueness;
use Phalcon\Mvc\Model\Validator\InclusionIn;

class Robots extends Model
{
    public function validation()
    {
        // Type must be: droid, mechanical or virtual
        $this->validate(
            new InclusionIn(
                [
                    'field'  => 'type',
                    'domain' => [
                        'droid',
                        'mechanical',
                        'virtual',
                    ],
                ]
            )
        );

        // Robot name must be unique
        $this->validate(
            new Uniqueness(
                [
                    'field'   => 'name',
                    'message' => 'The robot name must be unique',
                ]
            )
        );
To this:
<?php

namespace Store\Toys;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Message;
// use Phalcon\Mvc\Model\Validator\Uniqueness;
// use Phalcon\Mvc\Model\Validator\InclusionIn;

use Phalcon\Validation;
use Phalcon\Validation\Validator\Uniqueness;
use Phalcon\Validation\Validator\InclusionIn;


class Robots extends Model {
  public function validation() {
    $validator = new Validation();

    // Type must be: droid, mechanical or virtual
    $validator->add(
      "type",
      new InclusionIn(
        [
          'message' => 'Type must be "droid", "mechanical", or "virtual"',
          'domain' => [
            'droid',
            'mechanical',
            'virtual',
          ],
        ]
      )
    );

    // Robot name must be unique
    // $this->validate(
    $validator->add(
      'name',
      new Uniqueness(
        [
          'field'   => 'name',
          'message' => 'The robot name must be unique',
        ]
      )
    );

Then exec this:
curl -i -X POST -d '{"name":"C-3PO","type":"droid","year":1977}' http://localhost/my-rest-api/api/robots

**Comment by apg007** [comment]
One more time... change this:
```php
// from https://docs.phalconphp.com/en/latest/tutorial-rest#models
 <?php

namespace Store\Toys;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Message;
use Phalcon\Mvc\Model\Validator\Uniqueness;
use Phalcon\Mvc\Model\Validator\InclusionIn;

class Robots extends Model
{
    public function validation()
    {
        // Type must be: droid, mechanical or virtual
        $this->validate(
            new InclusionIn(
                [
                    'field'  => 'type',
                    'domain' => [
                        'droid',
                        'mechanical',
                        'virtual',
                    ],
                ]
            )
        );

        // Robot name must be unique
        $this->validate(
            new Uniqueness(
                [
                    'field'   => 'name',
                    'message' => 'The robot name must be unique',
                ]
            )
        ); 
```

To this:

```php
 <?php

namespace Store\Toys;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Message;

// see: https://github.com/phalcon/cphalcon/issues/11464
// use Phalcon\Mvc\Model\Validator\Uniqueness;
// use Phalcon\Mvc\Model\Validator\InclusionIn;

use Phalcon\Validation;
use Phalcon\Validation\Validator\Uniqueness;
use Phalcon\Validation\Validator\InclusionIn;


class Robots extends Model {
  public function validation() {
    $validator = new Validation();

    // Type must be: droid, mechanical or virtual
    $validator->add(
      "type",
      new InclusionIn(
        [
          'message' => 'Type must be "droid", "mechanical", or "virtual"',
          'domain' => [
            'droid',
            'mechanical',
            'virtual',
          ],
        ]
      )
    );

    // Robot name must be unique
    // $this->validate(
    $validator->add(
      'name',
      new Uniqueness(
        [
          'field'   => 'name',
          'message' => 'The robot name must be unique',
        ]
      )
    );
```

Then exec this:

`
curl -i -X POST -d '{"name":"C-3PO","type":"droid","year":1977}' http://localhost/my-rest-api/api/robots
`

**Comment by Stretsh** [comment]
Not a great way for people who are interested in getting to know the framework to be introduced to it. Outdated tutorials...

**Comment by ninjapanzer** [comment]
@apg007 would you open a PR with these changes?

**Comment by niden** [comment]
This has been addressed. Thank you @apg007
