### ISSUE TITLE
[API] __wakeup() method 

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/docs#1464]
There are in all exception class an __wakeup method inhereted from PHP Exception, but this don't have this method [PHP Exception](http://php.net/manual/en/class.exception.php)
Even in Phalcon sources there is no such method
Should we remove this method from all exception classes?

**Comment by ninjapanzer** [comment]
@emiliodeg I moved this to the incubator https://github.com/phalcon/incubator/issues/842
