### ISSUE TITLE
Response setContext method not found ?

### ISSUE THREAD

**Issue by afdallismen** [phalcon/docs#1483]

**Comment by ninjapanzer** [comment]
Could you please provide a little more context @afdallismen 
- What file / url and section you are seeing the issue with

**Comment by afdallismen** [comment]
in this url : https://docs.phalconphp.com/en/3.2/application-micro,
in handlers section, there is example code that look like this :
```
$app->get(
    '/orders/display/{name}',
    function ($name) use ($app) {
        $context = "<h1>This is order: {$name}!</h1>";
        $app->response->setContext($context);
        $app->response->send();
    }
);
```

Could not find setContext method on response Api section either. Maybe typo with setContent ?
