### ISSUE TITLE
[NFR] Update all API docs

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/docs#1505]
Hi, I'm translating the doc API from English to Spanish and I found many inconsistencies between the [source code](https://github.com/phalcon/cphalcon/tree/master/phalcon) and its documentation

- Method without description
- Missing properties
- Methods with different types of data in their parameters
- The type of return is practically undocumented 

There is some possibility of rebuilding the API documents trying to correct all these problems? especially to avoid having to do twice the work

Thanks

**Comment by niden** [comment]
Closing in favor of [#1822]
