### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by michaelasumcinei** [phalcon/docs#1529]
Hello

My name is Michael Asumcinei and I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by niden** [comment]
@digitalplayer-steemit We only accept translations through our integration with crowdin 

https://crowdin.com/project/phalcon-documentation

The crowdin platform allows us to keep one source (english) and all translations are based on that. This ensures consistency in the documentation.

We would love to see your contributions on that.

Thanks

**Comment by ghost** [comment]
Hello, sorry but i didn’t sent you any email.
Please send me a copy a mail received through our server. May be a pirated one.


Cordialement,
---------------------------------------------------
Jean-Michel Langé



Le 4 févr. 2018 à 18:30, Nikolaos Dimopoulos <notifications@github.com> a écrit :

@digitalplayer-steemit <https://github.com/digitalplayer-steemit> We only accept translations through our integration with crowdin

https://crowdin.com/project/phalcon-documentation <https://crowdin.com/project/phalcon-documentation>
The crowdin platform allows us to keep one source (english) and all translations are based on that. This ensures consistency in the documentation.

We would love to see your contributions on that.

Thanks
