### ISSUE TITLE
Requesting Filipino Translation 

### ISSUE THREAD

**Issue by cortesclintmark** [phalcon/docs#1534]
Allow me to contribute in your open source project into Filipino via Github.

**Comment by lucasff** [comment]
You need to create the content on a fork and submit a pull request back. Or use Crowdin interface adding the Filipino version.

**Comment by ergiegonzaga** [comment]
Hi sir, may I help with the translations to Filipino too sir?

**Comment by cortesclintmark** [comment]
@lucasff Sir, I would like to apply as a proofreader in your project which is the Phalcon Documentation in the crowdin. Please approve me sir

**Comment by niden** [comment]
The Filipino language is already available in Crowdin.
