### ISSUE TITLE
Requesting for a Filipino/Cebuano Translation PRoject

### ISSUE THREAD

**Issue by vinzruzell** [phalcon/docs#1537]
HI sir. I would like to request to have a project in here for filipino/cebuano translation.

**Comment by niden** [comment]
We use Crowdin for our translations. The language is available there and you can contribute as much or as little as you want.

https://crowdin.com/project/phalcon-documentation

**Comment by vinzruzell** [comment]
Hi sir..pls enable me as proofreader in filipino. I will do my best for
this thank you.
