### ISSUE TITLE
[NPR] Regenerate API documentation

### ISSUE THREAD

**Issue by emiliodeg** [phalcon/docs#1569]
Hi there I offer myself to make the necessary arrangements to be able to generate a new format of the documentation of the API improving the one that we have at the moment. I do not have too much free time on a daily basis but this documentation is currently outdated and is necessary to facilitate the use of Phalcon and to continue to grow the community of developers

### Goals
- Generate a new API documentation
- Full code coverage
- Correct definition of parameters, exceptions and return values
- Complete description of classes, interfaces, traits, etc.
- Complete description of methods, constants and properties

### Documentation Generators
- [ApiGen](https://github.com/ApiGen/ApiGen) [example](http://www.apigen.org/ApiGen/)
- [phpDocumentor](https://www.phpdoc.org/) [example](http://demo.phpdoc.org/Clean/)

It is not a big problem to generate the documentation based on the PHP code, I mean, the generator that we choose would be secondary, the main problem (I think) is in the generation of the PHP code found in the [repository ide-stubs](https://github.com/phalcon/ide-stubs) 
@sergeyklay How do you generate all that code?

Well, tell me if you like this idea or if you prefer to collaborate in another way

**Comment by sergeyklay** [comment]
We use `zephir stubs` to generate IDE stubs.

**Comment by niden** [comment]
ApiGen, phpDocumentor and others are great tools. The only problem is that most if not all need to scan PHP code and some use Reflection to retrieve the classes, methods and docblocks to produce this documentation.

Phalcon's source code is `zep` files i.e. Zephir which does not work with reflection.

If we can find a tool that can scan the sources (zep) and extract the class name, methods, interfaces etc. from it along with the docblock comments then the documentation (for the API) would be perfect.

Right now the generator does have some bugs but none of us really had enough time to sit down and iron them out. :(

**Comment by niden** [comment]
I would love to be able to find a tool that can do the above

**Comment by emiliodeg** [comment]
@niden and if we use `zephir stubs` to generate all the PHP code of the API and then with this make the API documentation using ApiGen or another?

**Comment by niden** [comment]
Closing in favor of [#1822]
