### ISSUE TITLE
How to search Phalcon PHP documentation site in my own language only?

### ISSUE THREAD

**Issue by tturnerdev** [phalcon/docs#1593]
How do I make Phalcon PHP Doc site search only return results in my language?

Example:
- I go to https://docs.phalconphp.com/en/3.3
- I then search in "google search" box for "volt"
- This makes request: https://docs.phalconphp.com/search?q=volt
- Several results are same page, but in different locale

Would be nice if we could force search in our local (maybe if referrer containing '/en/'?) such as:
https://docs.phalconphp.com/en/search?q=volt
https://docs.phalconphp.com/search/en?q=volt
https://docs.phalconphp.com/search?l=en&q=volt

I searched a bit, but I was unable to figure it out...

**Comment by tturnerdev** [comment]
My current solution is creating a custom search engine in Chrome:
- Settings > Manage search engines > Other search engines > ADD
Configure:
- Search engine: Phalcon Docs 3.3
- Keyword: phalcon
- URL: https://www.google.com/search?q=volt+site%3Ahttps%3A%2F%2Fdocs.phalconphp.com%2Fen

This issue could be marked as feature request if my original request is not currently possible.
Otherwise, feel free to close this if _won't do_

**Comment by niden** [comment]
@ronindesign As far as Google is concerned I have not found anything that would resolve the issue that you described. One can change the language of Google's results but that would be for every search sadly. 

I am going to close this for now. When I have some time I would like to experiment with elasticsearch or algolia.
