### ISSUE TITLE
Request filter not filtering (int) properly

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#1595]
_From @quasipickle on February 27, 2018 17:43_

This isn't a bug, but an issue with the documented and actual behaviour.

When filtering a request variable:

```php
$this->request->getPost('barcode','int');
```
one would expect the result of that to be an integer, or at least an integer-like string.  Casting to (int) would do the trick, but the filter just strips out non-integer characters.

So a POSTed variable of `-------234---34-888833--------------` would pass through.  That is clearly not an integer.

_Copied from original issue: phalcon/cphalcon#13309_

**Comment by sergeyklay** [comment]
_From @andrew-demb on February 28, 2018 9:25_

Phalcon uses PHP `filter_var()` function with flag `FILTER_SANITIZE_NUMBER_INT` to sanitize integer values. So, this is PHP behaviour.

```php
echo filter_var('-------234---34-888833--------------', FILTER_SANITIZE_NUMBER_INT);
// -------234---34-888833--------------
```

**Comment by sergeyklay** [comment]
_From @quasipickle on February 28, 2018 16:3_

Ah, I see.  I still propose this be changed to casting to an integer.  In my brain, this
```php
$this->request->getPost('barcode','int');
```
means "give me an integer representation of the string", not "give me a string with only integer-type characters in it".

**Comment by sergeyklay** [comment]
_From @andrew-demb on March 1, 2018 9:20_

Use `int!` to force cast. It will use `intval()`, and result for your data is 0, but it responsible for casting

**Comment by sergeyklay** [comment]
_From @quasipickle on March 1, 2018 15:41_

Thanks for that information.  I'm aware how to get around the issue, but that doesn't mean I believe it to still be an issue.  It's semantically misleading.

**Comment by niden** [comment]
This has been addressed in the docs
