### ISSUE TITLE
Create 3.4 branch

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#1617]
#### Add missed docs

- [x] [`Phalcon\Crypt::__construct`](https://github.com/phalcon/cphalcon/pull/13388)
- [x] [`Phalcon\Crypt::setHashAlgo`](https://github.com/phalcon/cphalcon/pull/13388)
- [x] [`Phalcon\Crypt::getHashAlgo`](https://github.com/phalcon/cphalcon/pull/13388)
- [x] [`Phalcon\Crypt::useSigning`](https://github.com/phalcon/cphalcon/pull/13388)
- [x] [`Phalcon\Crypt::getAvailableHashAlgos`](https://github.com/phalcon/cphalcon/pull/13388)
- [x] [`Phalcon\Http\Cookie::setSignKey`](https://github.com/phalcon/cphalcon/pull/13367) 
- [x] [`Phalcon\Http\Response\Cookies::setSignKey`](https://github.com/phalcon/cphalcon/pull/13367) 
- [x] [The ability to listen authorization events](https://github.com/phalcon/cphalcon/pull/13331)
- [x] [Response reason phrase](https://github.com/phalcon/cphalcon/pull/13314)
- [x] [`Phalcon\Loader::setFileCheckingCallback`](https://github.com/phalcon/cphalcon/pull/13361)

**Comment by emiliodeg** [comment]
Remove branches 3.1, 3.2 and 3.3 on crowdin???

**Comment by sergeyklay** [comment]
@emiliodeg No, because we need translations for 3.1, 3.2 and 3.3. These versions may have its own unique content.

**Comment by niden** [comment]
This has been addressed
