### ISSUE TITLE
API method signatures need different styles than method descriptions

### ISSUE THREAD

**Issue by zachleigh** [phalcon/docs#1653]
This is just impossible to read.
<img width="457" alt="screen shot 2018-06-06 at 10 39 17" src="https://user-images.githubusercontent.com/5616626/41011090-15b7ab2c-6976-11e8-8e81-f3f85d361036.png">

There needs to be either a different style applied to the method signatures or some kind of page break. It currently just looks like a wall of grey text and is really hard to scan through.

**Comment by niden** [comment]
Closed in favor of [1822]
