### ISSUE TITLE
[REQUEST] Phalcon PHP 3.4.0 - PDF Documentation

### ISSUE THREAD

**Issue by ghost** [phalcon/docs#1654]
Can you please update PDF docs to latest version ? I don't like the new official website docs, also prefer to have offline docs. You should try making docs on official website more usable like for example; http://devdocs.io/phalcon~3/

The latest I could find was 3.1.1 from
https://readthedocs.org/projects/phalcon-php-framework-documentation/

Thank You!

**Comment by niden** [comment]
Closed in favor of [1822]
