### ISSUE TITLE
Incorrect/incomplete documentation about Pdo adapter

### ISSUE THREAD

**Issue by quasipickle** [phalcon/docs#166]
This page:https://github.com/phalcon/docs/blob/master/en/api/Phalcon_Db_Adapter_Pdo.rst

The code example for executePrepared() does not have the 3rd required parameter.

Neither does the MySQL adapter example: https://github.com/phalcon/docs/blob/master/en/api/Phalcon_Db_Adapter_Pdo_Mysql.rst.

**Comment by SidRoberts** [comment]
Fixed in https://github.com/phalcon/docs/commit/cc420b8d460c8353355c2ed1919f76898fef6cda.
