### ISSUE TITLE
where's the simple chinese documents?

### ISSUE THREAD

**Issue by wiidz** [phalcon/docs#1687]
where's the simple Chinese documents?
i entered in the zh folder,but i couldn't find it.
And I saw the documents had ben updated in 25 days ago ,what's up ?

**Comment by niden** [comment]
The translations for Chinese and other languages are handled by Crowdin (https://crowdin.com)

https://crowdin.com/project/phalcon-documentation/zh-CN#

We update the docs site regularly. I have updated it earlier this week and today. What makes you say that it has not been updated? Can you please let me know what is not correct?
