### ISSUE TITLE
Misleading documentation for $response->redirect()

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/docs#1696]
Hello there,

Documentation page of [Request component](https://docs.phalconphp.com/en/3.3/response#redirections) says:
>Note that a redirection doesn't disable the view component, so if there is a view associated with the current action it will be executed anyway. You can disable the view from a controller by executing `$this->view->disable()`.

If you take a look at [`response.zep`](https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/phalcon/http/response.zep#L514) you will find this chunk of code inside `redirect` method body:
```
if dependencyInjector->has("view") {
    let view = dependencyInjector->getShared("view");
    if view instanceof ViewInterface {
        view->disable();
    }
}
```
So obviously docs is wrong as redirect does indeed disable the `view` component.

**Comment by niden** [comment]
Thank you for reporting this. It has been addressed
