### ISSUE TITLE
Possible necessary addition to PHQL docs

### ISSUE THREAD

**Issue by quasipickle** [phalcon/docs#175]
Hi,

I'm using PHQL in my command line application.  When I used this:

```php
$Query = new Phalcon\Mvc\Model\Query($sql, $this->di);
```
I got an error saying wrong number of errors, and that "PHQL Statement cannot be NULL".

When I changed that to
```php
$Query = $this->modelsManager->createQuery($sql);
```
The query ran just fine.

So, is this a failure of __MY__ code, a bug in Phalcon, or an omission in the docs?

**Comment by SidRoberts** [comment]
This appears to have been fixed.
