### ISSUE TITLE
API documentation: Better parser

### ISSUE THREAD

**Issue by niden** [phalcon/docs#1822]
Need to get a better parser for the API documentation

Goals:
- parse properly all the docblocks
- method list (visibility, name, parameters, description, return value)
- properties list (type, name, default value, description)
- show examples
- work on the CSS to outline the code better
- produce additional formats such as PDF
- utilize phpDocumentor to work on the docblocks
- potentially use the ide-stubs as the source of the API documentation

**Comment by niden** [comment]
I have been working on a better way to get our API documentation produced.

The problem we have is that any docblock parser or even reflection do not work on zephir sources/files. We have a parser that generates the stubs etc. but that is far from perfect.

I have been experimenting with using the `ide-stubs` as the source of the API documentation. Using phpDocumentor I can then get all the necessary information and print them out on screen using our markdown files.

The tricky part would be when releasing. Generating new ide-stubs and then checking whether anything has changed between the new version and the existing version. Any changes will need to be moved over and then a task (what I am working on) would run to produce the API documentation.

If we manage to keep the ide stubs in sync with Zephir code, the maintenance will be very trivial.

More to come on this

@emiliodeg @ninjapanzer

**Comment by emiliodeg** [comment]
I think the best solution (or the fastest) is to generate the API from the ide-stubs

From what I have seen we should improve the documentation in the Zephir code further so that the ide-stubs are better documented and therefore we have a more interesting API

Tell me how do you want me to help you with this?

**Comment by niden** [comment]
I have been running some tests with some sample code on my local regarding this. 

Yes the approach I am taking is through the `ide-stubs`. My goal is to remove the documentation from the zephir sources or even have some sort of unique identifiers there or something like that. Then we can generate the ide-stubs through that.

After that we will need to run a diff from the existing stubs to the generated ones so that we can offer the new functionality to phpstorm and to the API documentation.

I have been playing with phpDocumentor and querying those ide-stubs (the ones I created/updated) and it seems to be working really well. The best part is that I can export the phpDocumentor results to XML and then use that XML to display the results on screen the way we want to (or work with the template engine of phpDocumentor) .

A sample:

![image](https://user-images.githubusercontent.com/1073784/45627248-8755b280-ba5f-11e8-80dc-476166fc4c0c.png)

And these are the stubs:

![image](https://user-images.githubusercontent.com/1073784/45627293-a3f1ea80-ba5f-11e8-9864-a064c39f5138.png)

**Comment by niden** [comment]
Where I will need help is to check all the Zephir sources manually that they correspond with the correct docblocks for the ide-stubs. We can also work to enhance them by adding more examples on them.

One current limitation that phpDocumentor has is that for now it does not recognize @link or @see. I know they are working on this but I might have to try phpDocumentor 1 to get all the docs in order.

**Comment by niden** [comment]
Finally, what I wanted to do is put some logical structure in the API documents.

I was thinking (in this order):

- Show all the constants (alphabetical) with their values
- Show all the public properties (alphabetical) with any default values and types
- Show all the protected properties (alphabetical) with any default values and types
- Show all the public methods (alphabetical) with any default values and types
- Show all the protected methods (alphabetical) with any default values and types

I believe this will be a bit of a pain to rearrange the code so that everything shows alphabetically but it will allow our readers an easier way to find the content while reading it.

Thoughts?

**Comment by emiliodeg** [comment]
I would use phpdocumentor 3, although it is in an alpha state, we will have a longer support and they say they will support all the @ tags

The `ide-stubs` are generated by this command `zephir stubs`? in that case we should not check the whole code manually but a smaller amount

I agree to reorder the constants, properties and methods

**Comment by niden** [comment]
Yes the stubs are generated with that command. I think that at least initially we will have a lot of work to ensure that everything is in "sync" but for subsequent versions whenever a PR is issued to the cphalcon repository we can update the stubs to keep them all in sync. This will negate the need to run the stubs command to generate them.

Yes I agree about the phpdocumentor 3. That should work just fine.

**Comment by emiliodeg** [comment]
> subsequent versions whenever a PR is issued to the cphalcon repository we can update the stubs to keep them all in sync

Sorry, I didn't undersatnd. If then the ide-stubs are not generated with that command, are we going to maintain manually?

**Comment by niden** [comment]
I am thinking yes. The reason behind this is that when we change something to the cphalcon repository, we should also update the stubs respectively. This way we don't have any changes.

I know this will be a big task at least for the beginning but I think we can make it. 

The alternative of course is to find a way to parse the sources with the `zephir stubs` command, then compare it with the ide-stubs and apply the differences.

If we move all the docblocks from the zephir sources to the ide stubs then the only thing we will have to worry about is the method signatures or any new components.

What are your thoughts?

**Comment by niden** [comment]
@phalcon/documentation

**Comment by emiliodeg** [comment]
I think we should give the `zephir stubs` a last chance because it would not only be useful for the Phalcon project but also for any other project developed in Zephir

**Comment by niden** [comment]
I just don;t want to reinvent the wheel. Right now:

Parse zep files
-> produce ide-stubs
-> run phpdocumentor
-> produce documentation

The `zephir stubs` definitely needs some love because it is not perfect. We can work to make it perfect for sure.

The approach I was proposing above is that we keep the docblocks for the API in the `ide-stubs` only and keep things in sync manually as we write code.

**Comment by emiliodeg** [comment]
It's ok for me

**Comment by niden** [comment]
@emiliodeg brief update. I have been trying to get everything sorted out with the structure I want to retrieve (xml or json or whatever that is) so that I can get the documentation the way I want to (See screenshots above).

I spoke to Serghei and zephir does not only create `stubs` but there is also the `api` command that can generate api documentation based on templates. 

I am investigating all that functionality since honestly i didn't know that it was there (the api) and see if it will help with what I need or I can expand it so that it offers a JSON structure back (or XML).

Stay tuned.

**Comment by niden** [comment]
This has been addressed with a new parsing script in the cphalcon repo

https://github.com/phalcon/cphalcon/blob/4.0.x/tests/_ci/generate-api-docs.php
