### ISSUE TITLE
Old docs 1.3.4 stable

### ISSUE THREAD

**Issue by Raven0us** [phalcon/docs#2031]
Hi,

I can't seem to find any docs for Phalcon 1.3.4. https://olddocs.phalconphp.com seems to have 2.0.0 docs only.

Any idea where I could get them?

**Comment by niden** [comment]
I don't think we have them anymore, since the last v1.x version was more than 4 years ago :/

**Comment by niden** [comment]
There might be a chance to get them but it will be a pain to do so, just go to the master branch of the docs and start going back in the commit history. That is the only way I think that you might be able to get them.

**Comment by Raven0us** [comment]
I managed without docs, design was decent, so I didn't have a hard time figuring out how some things worked, although it was my first encounter with Phalcon.

Will do what you suggested, should I need anything.

**Comment by niden** [comment]
@Raven0us Feel free to catch up with us on our discord server https://phalcon.link/discord.

In all honesty your project should really be upgraded. 1.x is way too old, but that is just me.
