### ISSUE TITLE
v4: Rewrite contributions.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2089]
https://phalcon-docs4.netlify.com/4.0/en//contributions

**Comment by ruudboon** [comment]
Can we add a sections to the contribution how to contribute to the documentation and one for translating?

**Comment by niden** [comment]
cc @CameronHall @ruudboon

Comments and review please :)

**Comment by CameronHall** [comment]
Should we remove the PR checklist and add that/or a working example to the pull-requests one instead and just leave a reference to it on that page? Doesn't seem very DRY 😉

**Comment by niden** [comment]
I don't mind not being DRY in the documentation. I will add a link to the npr file

**Comment by niden** [comment]
Implemented

**Comment by ruudboon** [comment]
>  If your language is not listed, please send us a message so that we can add it.

Can we link to where to contact the team, or change it to open an issue at Github?

The latest point of the bullet check list has a double slash in the link. It looks like it's working but I think this could cause some issues.
> More information here
