### ISSUE TITLE
v4: Rewrite installation.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2127]

**Comment by ruudboon** [comment]
Thnx @niden! Looks good in general. Some small things.

https://docs.phalconphp.com/4.0/en/installation-requirements-software
Debian copy example holds next row "and then try and install Phalcon again"

https://docs.phalconphp.com/4.0/en/installation-platforms
Add FreeBSD (Unix) here or change Linux title to Linux/Unix? 
https://www.freebsd.org/cgi/ports.cgi?query=phalcon&stype=all

https://docs.phalconphp.com/4.0/en/installation-shared
Maybe we can remove cheap here, we cannot look into somebody's wallet and there could be more options why you wanna use shared hosting besides pricing. 
Maybe we could also ask people to ask there shared hosting company to install it. Besides that it could be helpful for our users if we try to get Phalcon added by default control panels (CPanel / DirectAdmin / Plesk)

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/docs/issues/2322
