### ISSUE TITLE
v4: Rewrite new-feature-request.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2133]
https://phalcon-docs4.netlify.com/4.0/en//new-feature-request

**Comment by niden** [comment]
cc @CameronHall @ruudboon

Comments and review please :)

**Comment by CameronHall** [comment]
> In the following cases a new feature request will be rejected **if**:

> New Feature requests explain the goal of the intended implementation and ~~open~~ **starts a** discussion on how best to implement it.

**Comment by niden** [comment]
Implemented
