### ISSUE TITLE
v4: Rewrite new-pull-request.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2134]
https://phalcon-docs4.netlify.com/4.0/en//new-pull-request

**Comment by niden** [comment]
cc @CameronHall @ruudboon

Comments and review please :)

**Comment by CameronHall** [comment]
> ~~fux~~ **fix** a bug (current issue)

> Your ~~Pull~~ **pull** request must include:

>Your Pull request must ~~include~~:
>
> * ~~Issued to~~ **target** the correct branch.
> * Update ~~to~~ the **relevent** CHANGELOG.md
> * **Contain** unit tests
> * **Updates to the** documentation ~~if necessary~~ and usage examples **as necessary**

> For new functionality, ~~again~~ we will need to have an issue created and referenced. If the functionality you are introducing collides with the philosophy and implementation of Phalcon, the pull request will be rejected.

> Additionally any new functionality that introduces breaking changes will be rejected at least for the current version but could very well be implemented in the next major version.

Instead of saying it will be rejected, the PR should be updated to target the next major version. That way it's not "wasted work" and doesn't need to be revived later on.

> It is highly recommended to discuss your NFR and PR with the core team and most importantly with the community ~~so as~~ to get feedback, guidance and **support** to work on a release plan that will benefit everyone.

Also if I'm being to be super picky any instance of "Github" should be "GitHub".

**Comment by niden** [comment]
These have been addressed

**Comment by ruudboon** [comment]
Nothing found that hasn't been already fixed. 👍
