### ISSUE TITLE
v4: Rewrite reproducible-tests.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2138]
https://phalcon-docs4.netlify.com/4.0/en//reproducible-tests

**Comment by niden** [comment]
cc @CameronHall @ruudboon

Comments and review please :)

**Comment by CameronHall** [comment]
>Remember to outline in the script the methodology you use to register the db service:
Can we please rephrase this? It doesn't make a lot of sense to me. If I'm misunderstanding it, I'm sure plenty of other people will too.

> You can provide your own database schema or even better**,** use any of the existing schemas in our testing suite (located in tests/_data/assets/db/schemas/ in the repository).

Other than that it looks good to me.

**Comment by niden** [comment]
Implemented
