### ISSUE TITLE
v4: Rewrite request.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2139]
https://docs.phalconphp.com/4.0/en/request

**Comment by niden** [comment]
cc @CameronHall @ruudboon Comments please

**Comment by ruudboon** [comment]
Great update!
Few small things.
**request-getting-values.md**
To easily see the order of the parameters can we add something like this?

- get($name=null, $filters=null, $defaultValue=null, $notAllowEmpty=false, $noRecursive=false)

**request-getting-values.md**
Missing link to the api and explain what header is used for isAjax.

**request-information.md**
Missing api link

**Comment by CameronHall** [comment]
Couple of minor changes, besides that it looks good to me :)
**request-getting-values**
> All ~~(~~ except from getServer() accept the following parameters:

**request-uploading-files**
> For the whole upload process to work, you will need to make the necessary changes to your php.ini.

Can we please elaborate a little on this?

**request-events**
> When using HTTP authorization, the Authorization header has the following format:
>
> ```Authorization: <type> <credentials>```
>
> Name | Example
> -------|-----------
> `<type>` | `Basic`
> `<credentials>` | `dXNlcm5hbWU6cGFzc3dvcmQ=`
>
> Additional authentication types are described in IANA registry of Authentication schemes and Authentication for AWS servers (AWS4-HMAC-SHA256).
>
> In ~~99.99%~~ **most** use cases the authentication type is:

Can we consider rephrasing it a little or changing it to the above?

**Comment by niden** [comment]
Resolved
