### ISSUE TITLE
v4: Rewrite volt.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2155]

**Comment by ruudboon** [comment]
This page contains a link to [album-o-rama](https://album-o-rama.phalconphp.com) this link is broken for a long time. Remove demo page or fix ssl? https://github.com/phalcon/album-o-rama/issues/15

**Comment by niden** [comment]
Remove demo I would say. All those applications need to be revisited.

**Comment by niden** [comment]
Resolved
