### ISSUE TITLE
Something seems to have changed

### ISSUE THREAD

**Issue by dongasai** [phalcon/docs#2173]
V3.4.*  missing
What should I do?

**Comment by dongasai** [comment]
in crowdin

**Comment by niden** [comment]
@dongasai The 3.4 project is no longer going to be translated. All translations are already on the site.

v4 is the new one that we are working on. Do not worry, all the translations you had before are there so when reviewing a document you can just click an existing translation and approve it.

For now only a few documents have been rewritten for v4. Those are:
* acl
* new-pull-request
* new-feature-request
* reproducible-tests
* contributions

Working on the rest of them

**Comment by niden** [comment]
More will come soon as soon as I review them :)
