### ISSUE TITLE
bad links on main acl page

### ISSUE THREAD

**Issue by tempcke** [phalcon/docs#2195]
On this page: https://docs.phalconphp.com/4.0/en/acl

Most of the links are wrong.

for example 'Creating an ACL' links to https://docs.phalconphp.com/4.0/en/setup when it should be https://docs.phalconphp.com/4.0/en/acl-setup I think.
same with nearly all the others, they are missing 'acl-'

**Comment by tempcke** [comment]
I would have tried to edit it myself however the edit on github link is gone and there is now an 'edit on crowdin' link which is also a bad link.

**Comment by niden** [comment]
Thanks @tempcke. I have pushed an update up. It should be done once the deployment finishes (usually 15 mins).

FYI if you want to issue a PR here, you can do so in the `/en` folder and that will propagate to all other translations.

**Comment by ruudboon** [comment]
Main links are working now. Links in right side bar are broken (using Anchors instead of uri).

**Comment by niden** [comment]
This has been fixed also. I just pushed the update. I only need to combine the first page with overview and that should be OK

**Comment by ruudboon** [comment]
Confirmed that the links are working. Will close this issue. Combining pages is not related to this one.
