### ISSUE TITLE
3.4.x docs:  menu anchors are broken.  

### ISSUE THREAD

**Issue by jellisii** [phalcon/docs#2196]
To use an example, `https://docs.phalconphp.com/3.4/en/volt` has two menus on the left.  The second menu appears to be for anchors in the page, but links resolve to a 404.  

EG:  The second link in the second menu, `https://docs.phalconphp.com/3.4/en/volt/introduction` appears that it should be `https://docs.phalconphp.com/3.4/en/volt#introduction`.  

This seems to be pretty consistent across the current documentation site.  Code inspection reveals the anchor tags to actually be in place, but the links that seem to be designated to point to them are broken.  

-- edit: clarity

**Comment by niden** [comment]
I believe I fixed this one. All the 3.x pages now have the correct anchors.

@jellisii can you  double check just in case please?

**Comment by jellisii** [comment]
Looks good from here in the few places I checked.  Thanks for fixing this. :)
