### ISSUE TITLE
Wrong link 'edit on crowdin'

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs#2201]
On the original EN documentation the link _edit on github_ is correct.
If you switch to a different language it changes to _edit on crowdin_ this link is incorrect

### Expected and Actual Behavior
Links to correct project on crowdin
_edit on crowdin_ changed to _translate on crowdin_

**Comment by CameronHall** [comment]
Fixed in https://github.com/phalcon/docs-app/pull/140. Thank you @ruudboon!
