### ISSUE TITLE
Improve styling next and previous page

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs#2222]
To improve the navigation we could highlight the next and previous page and style it a bit better.

- [x] Make styling suggestion
- [ ] Create styling pull request

**Comment by ruudboon** [comment]
How about this? ( a bit better aligned but I'm not a hero in Photoshop)
![navigation-example](https://user-images.githubusercontent.com/7444246/52257095-93141980-2919-11e9-9034-b05e7622652b.png)

**Comment by niden** [comment]
@sergeyklay @Ahrell  What do you guys think?

**Comment by Arhell** [comment]
looks good, but I would combine the buttons with the arrows
to have a whole button
![1](https://user-images.githubusercontent.com/26163841/52419388-a5987980-2af8-11e9-9d85-7843f7793984.jpg)

**Comment by niden** [comment]
Resolved
