### ISSUE TITLE
URL Site Bug

### ISSUE THREAD

**Issue by LenoM** [phalcon/docs#2235]
https://docs.phalconphp.com/en/latest/reference/routing.html
https://docs.phalconphp.com/en/latest/reference/dispatching.html
https://docs.phalconphp.com/en/latest/reference/queue.html
https://docs.phalconphp.com/en/latest/reference/micro.html
https://docs.phalconphp.com/en/latest/reference/cookies.html

**Comment by niden** [comment]
These have been fixed.

Thank you @LenoM
