### ISSUE TITLE
csrf token documentation update

### ISSUE THREAD

**Issue by Hopp3r** [phalcon/docs#2257]
Documentation should mention chrome specific problem:
https://forum.phalconphp.com/discussion/922/csrf-protection-not-working

Specifically:

> FINALLY after a long search I found it via the Zend CSRF bug in Chrome. What Chrome does is request the favicon.ico in the background. If it does not find it, it requests the page again and you get a new csrf token. The fix is adding the favicon.ico
> 
> ALSO: turn off the Web Inspector Tool. The CSRF check does not work with the toolbar open.
> 
> This bug I do not have in Firefox.

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/docs/issues/2322
