### ISSUE TITLE
UI issue in Phalcon 3.4.0 release documentation

### ISSUE THREAD

**Issue by NRDeshpande** [phalcon/docs#2261]
UI issue in Phalcon 3.4.0 release documentation (https://blog.phalconphp.com/post/phalcon-3-4-0-released).

The both "NOTE box" at the end of the page have extra ```</div>```
![phalcon](https://user-images.githubusercontent.com/17276419/54806632-992f4100-4ca0-11e9-93f1-0b3af9176360.jpg)
.

**Comment by Arhell** [comment]
fix

**Comment by niden** [comment]
Addressed
