### ISSUE TITLE
How do work Crowdin ?

### ISSUE THREAD

**Issue by ismail0234** [phalcon/docs#2265]
How do the validation process work after you've translation some files on the crowdin?

**Comment by niden** [comment]
@ismail0234 There are three proof readers in Crowdin for Turkish. Ahmet, Hidonet and Volkan. They will have to review your translations and approve them. After that your translations will become "live"

If you don't hear anything from them soon you can always send them a message through Crowdin.

If that does not work, let me know

**Comment by ismail0234** [comment]
@niden How can I contact them? I am could not find anywhere and How can I be proofreader?
