### ISSUE TITLE
Remove `Loader::registerDir()` references to something PSR4 compliant

### ISSUE THREAD

**Issue by SidRoberts** [phalcon/docs#2274]
I think we should replace mentions of `Loader::registerDir()` to `Loader::registerNamespaces()` in the application pages to be more [PSR4 compliant](https://www.php-fig.org/psr/psr-4/):

```php
 use Phalcon\Loader;

// Creates the autoloader
$loader = new Loader();

// Register some namespaces
$loader->registerNamespaces(
    [
        "Example\\Base" => "src/",
    ]
);

// Register autoloader
$loader->register();
```

**Comment by niden** [comment]
Agreed. I will get on it.

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/docs/issues/2322
