### ISSUE TITLE
Missing events from DB model events

### ISSUE THREAD

**Issue by FaimMedia** [phalcon/docs#2301]
The following doc is missing some events:
[https://github.com/phalcon/docs/blob/4.0/en/db-models-events.md](https://github.com/phalcon/docs/blob/4.0/en/db-models-events.md)
[https://docs.phalconphp.com/3.4/en/db-models-events](https://docs.phalconphp.com/3.4/en/db-models-events)

afterDelete:
[https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/model.zep#L3427](https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/model.zep#L3427)

beforeDelete:
[https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/model.zep#L3389](https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/model.zep#L3389)

afterFetch:
[https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/model.zep#L644](https://github.com/phalcon/cphalcon/blob/v3.4.0/phalcon/mvc/model.zep#L644)

Maybe I'm also missing some events, these were the ones that I've noticed right away.

Greetings!

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/docs/issues/2322
