### ISSUE TITLE
phalcon mvc view doc

### ISSUE THREAD

**Issue by cybor0** [phalcon/docs#234]
Example  on the page 
http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_View.html

<?php

    //Render the view related to the controller only
    $this->view->setRenderLevel(View::LEVEL_VIEW);

constant LEVEL_VIEW dosen't exist should be LEVEL_ACTION_VIEW

**Comment by andresgutierrez** [comment]
Fixed in master
