### ISSUE TITLE
Docs not available in (parts) of Russia

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs#2407]
Our users mentioned that since a day or 3 they are unable to open the docs from a Russian internet connection. It looks like Russia is blocking Netlify. Not sure why this only happening after the phalcon.io migration.

This website show's we're blocked.

https://isitblockedinrussia.com/?host=docs.phalcon.io

There are more reports about this issue in Netlify.

https://community.netlify.com/t/netlify-cdn-or-dns-blocked-in-russia/372/6

Let's use this issue to track our tests and solutions. User who have this issue also. Please comment with your location and ISP

**Comment by ruudboon** [comment]
Netlify confirmed there some issues regarding a block from Russia. We now proxied all the domain using cloudflare.

**Comment by Jeckerson** [comment]
Well, some times Cloudflare has same issues...

**Comment by ruudboon** [comment]
@Jeckerson yes I know, for now this look like the best option but I will keep monitoring this.
