### ISSUE TITLE
Bug in Basic Tutorial Documentation

### ISSUE THREAD

**Issue by petrovsa** [phalcon/docs#2510]
![77](https://user-images.githubusercontent.com/41642399/68656243-1eba7680-053a-11ea-8807-328d12c8a78d.png)
In tutorial-basic.md in all translates. String 'use Phalcon\Mvc\Url as UrlProvider' can be instead 'use Phalcon\Url'. In Video tutorial its Ok!

**Comment by Jeckerson** [comment]
Hi! Could you make PR?

**Comment by petrovsa** [comment]
I will try. I have never done this before

**Comment by Jeckerson** [comment]
Here is tutorial how to do that - https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by niden** [comment]
I just pushed the correction upstream. Thank you @petrovsa
