### ISSUE TITLE
Duplicated Symfony version in the Hello World

### ISSUE THREAD

**Issue by arianmaykon** [phalcon/docs#259]
At the Hello World chapter (http://docs.phalconphp.com/en/latest/reference/benchmark/hello-world.html) Symfony is quoted with the 2.0.11 version, but below the 2.1.6 version is "used", which is the correct one?

**Comment by SidRoberts** [comment]
For future reference, the benchmark pages have since been removed (see 45c570ebfde95f99b7f0c248dbb180c28d5a0003).
