### ISSUE TITLE
Database - PHQL Conditions section uses ORDER BY rather than WHERE

### ISSUE THREAD

**Issue by Chealer** [phalcon/docs#2594]
[The Conditions section of the page on PHQL](https://docs.phalcon.io/4.0/en/db-phql#conditions) starts with:

> Conditions allow us to filter the set of records we want to query using the WHERE keyword.
> 
> Select a record with a single numeric comparison:

```
<?php

$phql = "
    SELECT 
        *
    FROM 
        Invoices
    ORDER BY 
        Invoices.inv_cst_id = 1";

$records  = $this
    ->modelsManager
    ->executeQuery($phql)
;
```

Usage of ORDER BY instead of WHERE is puzzling, yet all following examples do the same. I am discovering Phalcon and cannot say for sure what it should be, but as this page used WHERE prior to a recent commit by @niden which does not mention this change in its description (5e1f38b191161edbe7e206bd61b82a81f9f03489), I suppose this is some strange accident. Unfortunately GitHub's diff viewer does not help clarify how that change was done on such a big diff.

**If** the code is right, surely the text should be adjusted to explain.

**Comment by niden** [comment]
You are right that should be a `WHERE` clause. Sometimes Copy-Paste programming fails :)

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/docs/commit/8f3c17c1017ed3137f48a6b08305c153baf761f9

**Comment by niden** [comment]
Thank you @Chealer

**Comment by Chealer** [comment]
Thanks to you for such a quick fix @niden 
That surely fixes it.
