### ISSUE TITLE
[BUG]: VoltService closure receive 1 parameter, 2 expected

### ISSUE THREAD

**Issue by kschnekenburger** [phalcon/docs#2600]
**Describe the bug**
Hi, 

I started migrate to 4.x.
When i set VoltService by following the [Documentation](https://docs.phalcon.io/4.0/en/volt#activation)
Like : 

``` php
$container->setShared(
    'voltService',
    function (ViewBaseInterface $view, DiInterface $container) {

````

I obtain an error ArgumentCountError type

```
ArgumentCountError: Too few arguments to function ....  1 passed and exactly 2 expected
```

closure didn't receive $container parameter
is this normal behavior?

**Details**
 - Phalcon version: 4.0
- PHP Version: 7.4.1
 - Operating System: Debian (Docker)
 - Installation type: Compiling from source 
 - Server: Apache

Thank And good Job for 4.x !

**Comment by Jeckerson** [comment]
@kevcomparadise you can use working example of Vokuro:

https://github.com/phalcon/vokuro/blob/master/src/Providers/ViewProvider.php#L44

**Comment by kschnekenburger** [comment]
OK, thanks !

**Comment by sergeyklay** [comment]
I reopen this issue because documentation still is outdated

**Comment by niden** [comment]
Addressed in : https://github.com/phalcon/docs/commit/9d5997add29aca90f69abaaccdb0271243b96c6c
