### ISSUE TITLE
The getRewriteUri() is removed from v4

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#2604]
I suggest that this information will be saved here https://docs.phalcon.io/4.0/en/upgrade

_Originally posted by @zak-wojtek77 in https://github.com/phalcon/cphalcon/issues/14655#issuecomment-569310137_

**Comment by niden** [comment]
https://github.com/phalcon/docs/commit/d82623a4d131b768c245c19c0b62cbb8f90d619e

Added
