### ISSUE TITLE
[BUG]: Model save() missed from upgrade docs

### ISSUE THREAD

**Issue by calinrada** [phalcon/docs#2616]
This is missing from the upgrade guide in v4 docs. I think It should be added asap. For example I have lost almost an hour trying to figure it out why the save() with params, wasn't working. I ended up checking the source code and realised that in v4, save() does not accept parameters anymore.

**Comment by ruudboon** [comment]
Looks like we missed this indeed. Thnx for reporting. We will add this.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/docs/commit/d6b9708877c57d1e40351c14e9c1ea5bb4de960f

Thank you @caiofralmeida
