### ISSUE TITLE
Unclear how to report issues

### ISSUE THREAD

**Issue by Chealer** [phalcon/docs#2632]
The documentation contains some information about issue tracking in [the Contributions page](https://docs.phalcon.io/4.0/en/contributions). That only covers bugs though and does not say where a certain issue would be tracked. While that is not hard to figure out for bugs in Phalcon, I for one cannot figure out where an issue in the website would be tracked.

**Comment by niden** [comment]
@Chealer Each issue is attached so to speak to the relevant repository. So if you find an issue in the main website, you can report it in the relevant repo. The same as devtools, main cphalcon etc.

HTH

**Comment by Chealer** [comment]
Thank you @niden 
Unfortunately the relevant repository is often unclear. For example, even I cannot figure out how an issue in [this blog post](https://blog.phalcon.io/post/phalcon-4-0-0-released) should be tracked. So either:
1. the repository should be clearly indicated for all possible cases
2. or a default/general/fallback repository should be designated for unclear cases

**Comment by niden** [comment]
Are you talking about the contents of the blog post or the blog post (text) itself? If it is the former, it relates to Phalcon, the extension so anything like that goes to the main repo (cphalcon). If it is for the blog post it should go to the blog repository.

I am sorry but I never had this question asked before so pardon for the reluctance.

You are more than welcome to open a PR in the docs repository (en directory) with verbiage that you would like to see in the docs.

**Comment by Chealer** [comment]
> 
> 
> Are you talking about the contents of the blog post or the blog post (text) itself? If it is the former, it relates to Phalcon, the extension so anything like that goes to the main repo (cphalcon). If it is for the blog post it should go to the blog repository.

Sorry, I do not understand the question. However, I did not mean this as a specific question or about a specific issue. I meant that the page should cover all issues which can affect the website (and possibly more).
> 
> I am sorry but I never had this question asked before so pardon for the reluctance.
> 
> You are more than welcome to open a PR in the docs repository (en directory) with verbiage that you would like to see in the docs.

If the solution is merely "verbiage", I unfortunately do not know what it is (for example, for an issue with a blog post).

**Comment by niden** [comment]
Here is what I mean - taking an example the link you posted. 

The link points to a blog post. If your correction, or issue or whatever you need to report, relates to the actual contents of the blog post, or there is a problem with the stylesheet, or something similar, you report it to the `blog` repository.

If however by using the link you want to report something that relates to the actual contents of the blog post which in this case it was the Phalcon v4 release (i.e. the extension) that goes to the cphalcon (main repository).

I hope this makes what I wrote a bit clearer.

All the sites we have relate to repositories in GitHub under the https://github.com/phalcon organization. I am pretty sure that all the descriptions are updated. If in doubt, just give us a shout here, discord, forum...

**Comment by Chealer** [comment]
> 
> 
> Here is what I mean - taking an example the link you posted.
> 
> The link points to a blog post. If your correction, or issue or whatever you need to report, relates to the actual contents of the blog post, or there is a problem with the stylesheet, or something similar, you report it to the `blog` repository.
> 
> If however by using the link you want to report something that relates to the actual contents of the blog post which in this case it was the Phalcon v4 release (i.e. the extension) that goes to the cphalcon (main repository).
> 
> I hope this makes what I wrote a bit clearer.

Ah, yes, I understood now, thanks @niden


> All the sites we have relate to repositories in GitHub under the https://github.com/phalcon organization. I am pretty sure that all the descriptions are updated. If in doubt, just give us a shout here, discord, forum...

Looking at this, I do think the vast majority of issues do have a proper ITS to track them, so the issue does seem to be merely explaining how to determine which kind of issue goes to which ITS (repository).
Regarding the case of the blog, [its repository](https://github.com/phalcon/blog) describes it as "The engine behind Phalcon's blog". But looking at its contents, this seems to contain the blog itself (including its data), not a (generic) blog engine. I would recommend to change that to "The source behind Phalcon's blog", or just "Phalcon's blog".

**Comment by niden** [comment]
Ok now I get it. I changed the description to `Phalcon Framework's blog` HTH :)

**Comment by Chealer** [comment]
Thank you @niden that does help.

**Comment by niden** [comment]
Anytime. Let us know if you have any additional thoughts or corrections we need to make :)

**Comment by niden** [comment]
Closing this

**Comment by Chealer** [comment]
Can the solution be clarified? I do not see much improvement.

**Comment by niden** [comment]
As per the above discussion, the issue was the description of the blog which has been fixed. 

The last comment was _Let us know if you have any additional thoughts or corrections we need to make :)_ Since there was no suggestion or anything like that we closed the issues.

If you have any specific suggestions or think that somewhere something needs to be added you can create a pull request or an issue pointing the omission(s)

**Comment by Chealer** [comment]
The issue with the description of the blog has indeed been fixed, but that was at best a "sub-issue" of the issue tracked here. In order to benefit from that change, reporters need to first land on that page. The core issue described in the first comment remains.

One alternative might be to direct the vast majority of issues to the proper ITS, and - if all issues have a corresponding repository - to direct others straight to the organizational page @niden linked to. I would hope this could be for less than 10% of cases though, as the list is big and unstructured.

**Comment by Chealer** [comment]
Could this ticket be reopened?
