### ISSUE TITLE
[Source on GitHub](links are broken for v4)

### ISSUE THREAD

**Issue by Deathamns** [phalcon/docs#2643]
Example: https://docs.phalcon.io/4.0/en/api/phalcon_acl#acl-adapter-abstractadapter

GitHub is case sensitive for its paths, Phalcon 4 uses CamelCase for file/folder names, but the links are in lowercase.

Currently:
https://github.com/phalcon/cphalcon/tree/v4.0.0/phalcon/acl/adapter/abstractadapter.zep

What it should be:
https://github.com/phalcon/cphalcon/blob/v4.0.0/phalcon/Acl/Adapter/AbstractAdapter.zep

**Comment by Deathamns** [comment]
https://github.com/phalcon/cphalcon/blob/v4.0.0/tests/_ci/generate-api-docs.php#L66

**Comment by diplopito** [comment]
This issue is still present. I sent to @niden the links fixed.
