### ISSUE TITLE
Phalcon\Storage\Adapter's constructor can't take NULL

### ISSUE THREAD

**Issue by wmamrak** [phalcon/docs#2659]
The cache page of the docs:
https://docs.phalcon.io/4.0/en/cache
mentions a few times that it is possible to create Storage\Adapter object with first argument being NULL, e.g.:
$adapter = new Apcu(null, $options);

This is prohibited because the type of first parameter is SerializerFactory (without `?`).

**Comment by niden** [comment]
@wmamrak Thank you for this. I will correct it

**Comment by niden** [comment]
This has been addressed. Thank you again @wmamrak

**Comment by wmamrak** [comment]
Good job!
