### ISSUE TITLE
Register dir in REST API page

### ISSUE THREAD

**Issue by mmarif4u** [phalcon/docs#266]
A little piece of information is missing from this page:
http://docs.phalconphp.com/en/latest/reference/tutorial-rest.html

It is not mentioned to register the dirs in Loader for example models etc.
Here is a bit explanation:
http://forum.phalconphp.com/discussion/1277/rest-api-notfound-problem#C4551

Thanks

**Comment by SidRoberts** [comment]
Added in db777541cf3b5d39089e3fc7f71c95d520fd64fa and 037df52e1b3dd603fe2748a5a9cb10f83e33baf6.
