### ISSUE TITLE
In v4, Algolia is returning v3.4 pages

### ISSUE THREAD

**Issue by diplopito** [phalcon/docs#2668]
When searching in https://docs.phalcon.io/4.0/en/introduction, i.e. fetchOne, Algolia is returning this page:
https://docs.phalcon.io/3.4/en/api/phalcon_db#methods-1
Which belongs to 3.4

**Comment by ruudboon** [comment]
I will have a look at this.

**Comment by ruudboon** [comment]
Everything is working fine again. Please reopen or create a new issue if you find any issues.

**Comment by diplopito** [comment]
It's failing again: please visit [Docs 4.0](https://docs.phalcon.io/4.0/en/introduction) and search for `microcollection`. Results returned will be for 3.4: https://docs.phalcon.io/3.4/en/api/phalcon_mvc_micro#class-phalconmvcmicrocollection
