### ISSUE TITLE
Error in Controller documentation 4.0?

### ISSUE THREAD

**Issue by chelipf** [phalcon/docs#2679]
In the phalcon 4.0 documentation, in the [Controller section](https://docs.phalcon.io/4.0/en/controllers) is said:

> An action is any public **class** in a controller with the Action suffix. These actions are accessible by a URL and are responsible for interpreting the request and creating the response. Usually responses are in the form of a rendered view, but there are other ways to create responses as well.

But, shouldn't it say "An action is any public **method / function** in a controller with the Action suffix..." instead?

In the same document there is a typo, invvoices instead of invoices.

**Comment by niden** [comment]
This was resolved in https://github.com/phalcon/docs/pull/2675
