### ISSUE TITLE
Typo in documentation Model Relationships v4

### ISSUE THREAD

**Issue by Phjester** [phalcon/docs#2689]
In page [https://docs.phalcon.io/4.0/en/db-models-relationships#model-relationships](url)

Section with next code:
`
namespace MyApp\Models;

use Phalcon\Mvc\Model;

class Products extends Model
{
    public $prd_id;
    public $prd_title;
    public $prd_price;
    public $prd_created_at;

    public function initialize()
    {
        $this->hasMany(
            'prd_id',
            Products::class,
            'ixp_prd_id'
        );
    }
}
`

I think that this entity cannot have a relation with itself. This is entity have relation with InvoicesProducts

**Comment by niden** [comment]
Resolved in 52322c192218f0514fd93fc14f535bc3dc4d35b4

**Comment by niden** [comment]
Thank you @Phjester
