### ISSUE TITLE
May there some mistakes for the Phalcon 4.0 events docs?

### ISSUE THREAD

**Issue by lanlin** [phalcon/docs#2690]
hi there, may there have some mistake for new docs? 
[list-of-events](https://docs.phalcon.io/4.0/en/events#list-of-events)
[dispatcher-events](https://docs.phalcon.io/4.0/en/dispatcher#events)

I find that dispatcher events listed are not the same, exp: `afterInitialize` & `initialize`.

and another question for the dispatcher events, does all events same for both CLI & MVC mode of the Phalcon 4.0?

**Comment by niden** [comment]
@lanlin Thank you for this. The two lists have been synched with the correct contents.

Also, I added a note for the `beforeForward` which exists only in MVC not CLI. The other events are all the same
