### ISSUE TITLE
Database Migrations section not in menu

### ISSUE THREAD

**Issue by edgarsstrods** [phalcon/docs#2691]
https://docs.phalcon.io/4.0/en/db-migrations section can not be found in side menu, so you do not know about this if not using search engine (as I discovered this).

**Comment by niden** [comment]
This has been resolved (hangout commit)


https://github.com/phalcon/docs-app/commit/bc8387893d373a9ef1b5398bb5df773506dff592

**Comment by niden** [comment]
Thank you @edgarsstrods
