### ISSUE TITLE
Incorrect sample of NotFoundMiddleware

### ISSUE THREAD

**Issue by Riu** [phalcon/docs#2729]
On page https://docs.phalcon.io/4.0/en/application-micro in section **Not Found (404) Middleware** is sample code, but it's not working. Fix for it:

```php
public function beforeNotFound(Event $event, Micro $app)
{
  $app->response->redirect('/404');
  $app->response->send();
  return false;
}
```

**Comment by niden** [comment]
@Riu Thank you. Corrected it.
