### ISSUE TITLE
Missing plugin documentation

### ISSUE THREAD

**Issue by ragnarlotus** [phalcon/docs#2744]
Hello!

The docs for https://docs.phalcon.io/4.0/en/api/phalcon_plugin#plugin returns 404. I checked it in the code and there is no file.

Thanks for your great work!

**Comment by niden** [comment]
Hello 

The Plugin class has been removed for v4. Have a look at this in the upgrade document

https://docs.phalcon.io/4.0/en/upgrade#mvcuser

**Comment by ragnarlotus** [comment]
Oh! then should be removed from https://docs.phalcon.io/4.0/en/api/

Thanks!

**Comment by niden** [comment]
Good catch. We missed that one. I will remove it.

**Comment by niden** [comment]
Removed. Thank you for the report!! @deulos
