### ISSUE TITLE
The parts that should not be translated have been translated

### ISSUE THREAD

**Issue by fagai** [phalcon/docs#2812]
https://github.com/phalcon/docs/blob/4.0/ja-jp/volt.md#logic

I think the operator contains Japanese and "または" is "or".
It didn't seem to be editable from Crowdin.

**Comment by niden** [comment]
Unfortunately things like that happen. We try to hide strings that are not meant to be translated but not always successful.

I have corrected the issue. We should be ok in the next push.

**Comment by fagai** [comment]
@niden thank you!
