### ISSUE TITLE
Truncated (long) sections names in table of contents

### ISSUE THREAD

**Issue by Chealer** [phalcon/docs#2950]
Phalcon's documentation has page-specific tables of contents (TOC-s), although it is discreet (as reported in ticket phalcon/documentation#36). Unfortunately, long section names are truncated at some point, as is evident in [Phalcon\Http's page for Phalcon 4.0](https://docs.phalcon.io/4.0/fr-fr/api/phalcon_http), for example with section _Abstract Class Phalcon\Http\Message\AbstractCommon_. This occurs in both Google Chrome and Firefox 90, even when the viewport's width more than suffices to display the full name, as can be seen in the following screenshot:
![image](https://user-images.githubusercontent.com/486141/128777231-a96f625e-1967-4b82-8faa-c5957b5511fd.png)

**Comment by niden** [comment]
@Arhell Can you have a look at this, see if we can make either the sidebar bigger or the text to wrap?

**Comment by Chealer** [comment]
@Arhell are you sure this solves the problem? I am not a CSS expert but do not see how overflow would help, and the problem visibly persists.

**Comment by Arhell** [comment]
> @Arhell are you sure this solves the problem? I am not a CSS expert but do not see how overflow would help, and the problem visibly persists.

There is another option, it is to do word wrap.
![10-11-2021 01-37-26](https://user-images.githubusercontent.com/26163841/141022928-73dbddd8-081a-49dd-902e-5cea6daa4a42.jpg)
but I don't really like this solution

**Comment by Chealer** [comment]
This persists on Phalcon's site (at least on the very page for which it was reported).

@Arhell I do not understand your answer, can you clarify? Are you really talking about this issue, and if so, is a solution for this supposed to be ready?

**Comment by Arhell** [comment]
> This persists on Phalcon's site (at least on the very page for which it was reported).
> 
> @Arhell I do not understand your answer, can you clarify? Are you really talking about this issue, and if so, is a solution for this supposed to be ready?

The screenshot above is a solution to this problem.

I don't like it, I corrected it in a different way.

**Comment by Chealer** [comment]
I am sorry @Arhell but I do not understand your solution. Can you tell us if your solution is deployed?

**Comment by Arhell** [comment]
> I am sorry @Arhell but I do not understand your solution. Can you tell us if your solution is deployed?

For a long time in production
https://docs.phalcon.io/4.0/fr-fr/api/phalcon_http#http-cookie

Maybe I misunderstood, I was thinking about tables, maybe you had something else in mind?

**Comment by Arhell** [comment]
A little later I will correct it again.
Came up with another solution.

It will be like this
with scrolling
![31-12-2021 01-55-11](https://user-images.githubusercontent.com/26163841/147795164-5f29b289-4d50-42a4-b60a-970d5ecff932.jpg)

**Comment by Chealer** [comment]
Thank you @Arhell for your clarification and for your solution

I am sorry but the term "table of contents" is misleading in this context. It does not actually refer to a table, but rather to a **list about the page's content**. That list can be seen at the left of my screenshot.

Unfortunately the page I chose to exemplify this issue also exemplified a different issue, tracked in ticket phalcon/documentation#12, and the work you did is on that different issue. I recommend:

- to reopen this ticket
- to report the work you did in ticket phalcon/documentation#12. If as you write your solution is already deployed, I recommend to keep phalcon/documentation#12 open, as it did not fully solve the issue for me.

**Comment by Chealer** [comment]
This is finally solved! Thanks again
