### ISSUE TITLE
https://nanobox.io/ broken link

### ISSUE THREAD

**Issue by Arhell** [phalcon/docs#2968]
https://github.com/phalcon/docs/blob/4.0/en/testing-environment.md
https://nanobox.io/

**Comment by Jeckerson** [comment]
Nanobox was bought be DigitalOcean and will be closed soon.

**Comment by Arhell** [comment]
> Nanobox was bought be DigitalOcean and will be closed soon.

Then can remove this link from the document?

**Comment by Arhell** [comment]
cc @niden

**Comment by Jeckerson** [comment]
yes
