### ISSUE TITLE
Tag Helpers example shows invalid syntax for {{ form() }} volt tag

### ISSUE THREAD

**Issue by JMoodyFWD** [phalcon/docs#3093]
The "Tag Helpers" section within the Volt docs is showing a {{ form() }} volt example which has 'action' assigned using an arrow `=>`, which causes a syntax error when volt compiles. The example should be showing 'action' assigned with a colon `:`

Posting this, along with screenshot of issue, per @niden 

![tag-helpers-example-typo](https://user-images.githubusercontent.com/8059176/195628416-47231685-f826-434f-bcb5-fe430c432a48.jpg)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/docs/commit/5d62270c864364296b840060d1bb3e9508c02a21
