### ISSUE TITLE
Phalcon 5.0 Getting Started "tags" Checkout Issue 

### ISSUE THREAD

**Issue by kgrammer** [phalcon/docs#3105]
The documentation for Phalcon 5.0 "Getting Started" has several references to:

     git checkout tags/v5.0.0 ./

These need to the following now that Phalcon 5.1.1 has been released:

     git checkout tags/v5.1.0 ./

**Comment by niden** [comment]
Addressed in 03f0ed396a5124b140d46e2222f5462155ef2b18

I added a warning for the commands to be adjusted accordingly. We cannot be changing the commands of the docs with every release so that one will suffice.

Thanks @kgrammer
