### ISSUE TITLE
[BUG]: Incorrect Function Reference on Flash Messages Documentation 

### ISSUE THREAD

**Issue by kgrammer** [phalcon/docs#3108]
In the V5.0 Flash Messages documentation (https://docs.phalcon.io/5.0/en/flash#overview), the section that describes setCssIconClasses(), the sample code snippet is showing a call to setCssClasses() when it should be calling setCssIconClasses().

The last line of the code snippet is:

$flash->setCssClasses($cssClasses);

It should be:

$flash->setCssIconClasses($iconClasses);

**Comment by niden** [comment]
Fixed in 73fc069efcffdfec80603204ffbbd9ed6ed4b72f

Thank you @kgrammer
