### ISSUE TITLE
Missing link for pagination - error 404 

### ISSUE THREAD

**Issue by borisdelev** [phalcon/docs#3114]
Hi there :)

Just notice that the documentation for pagination is missing: https://docs.phalcon.io/5.0/en/db-pagination .

![image](https://user-images.githubusercontent.com/4441663/206189040-ff11472c-ac3a-44df-b653-ae6328711662.png)

Well... this is it :) Thank you for great job uve done.
Greetings and... may the force be with you!

**Comment by niden** [comment]
Greetings!

Resolved in https://github.com/phalcon/docs/commit/043922edf40ba532015eb231c21bcc96a29bb35c and than you @borisdelev for reporting this.
