### ISSUE TITLE
[BUG] Wildcard roles in ACL

### ISSUE THREAD

**Issue by quasipickle** [phalcon/docs#317]
Documentation for ACL says a \* wildcard is allowable:

```
 //Allow access to any role to browse on products
 $acl->allow('*', 'products', 'browse');

 //Allow access to any role to browse on any resource
 $acl->allow('*', '*', 'browse');
```

But an exception gets thrown.  This was mentioned in the forum: http://forum.phalconphp.com/discussion/423/are-there-wildcards-in-acl-roles- but not acted on

**Comment by niden** [comment]
I cannot find this in the documentation any more. Based on how old this issue is, it has been corrected since.

Thanks for reporting it.
