### ISSUE TITLE
Gettext example is wrong

### ISSUE THREAD

**Issue by noone-silent** [phalcon/docs#3170]
In Phalcon 5 the `locale` is not a string anymore, it's an array of strings

https://docs.phalcon.io/5.0/en/translate#gettext

In the documentation this is wrong. If you pass locale as string you have an Exception with this message:

```php
TypeError: Phalcon\Translate\Adapter\Gettext::setLocale(): Argument #2 ($localeArray) must be of type array, string given
```

**Comment by niden** [comment]
This has been addressed. Thank you @noone-silent
