### ISSUE TITLE
Error in the last example of PHQL / Joins 

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/docs#325]
I'm trying to find a way to generate sql from phql, so far without luck. The last example in [PHQL#Joins](http://docs.phalconphp.com/en/latest/reference/phql.html#joins) says that:

```
$phql = 'SELECT Brands.name, Songs.name FROM Artists ' .
        'JOIN Songs WHERE Artists.genre = "Trip-Hop"';
$result = $this->modelsManager->query($phql);
```
Produce the following SQL in MySQL:
```
SELECT `brands`.`name`, `songs`.`name` FROM `artists`
INNER JOIN `albums` ON `albums`.`artists_id` = `artists`.`id`
INNER JOIN `songs` ON `albums`.`songs_id` = `songs`.`id`
WHERE `artists`.`genre` = 'Trip-Hop'
```

Does it demonstrate what happens in MySql or does it actually sets $result value to that string? 

The error seems to be the missing `query` method, perhaps the `executeQuery` was meant?

**Comment by SidRoberts** [comment]
Fixed in #618
