### ISSUE TITLE
Assets\Manager: VERY incomplete

### ISSUE THREAD

**Issue by kolypto** [phalcon/docs#334]
[Assets](http://docs.phalconphp.com/en/latest/reference/assets.html) page lacks the following:
- Examples on how to add assets and output them from templates
- Real-life minifying example (see [this issue](https://github.com/phalcon/cphalcon/issues/2009]) from volt
- Configuration options: sourceBasePath, targetBasePath

API page for [\Assets\Manager](http://docs.phalconphp.com/en/latest/api/Phalcon_Assets_Manager.html) lacks the following:
- Configuration options: sourceBasePath, targetBasePath
- Method `output()` is completely missing

API page for [\Assets\Collection](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Collection.html):
- Method `setPrefix()` is missing

Too bad users have to look into the sources to learn the above.

**Comment by SidRoberts** [comment]
(Will update accordingly)

[Assets](http://docs.phalconphp.com/en/latest/reference/assets.html) page lacks the following:

- [x] Examples on how to add assets and output them from templates
- [ ] Real-life minifying example (see [this issue](https://github.com/phalcon/cphalcon/issues/2009) from volt)
- [ ] Configuration options: sourceBasePath, targetBasePath

API page for [\Assets\Manager](http://docs.phalconphp.com/en/latest/api/Phalcon_Assets_Manager.html) lacks the following:

- [ ] Configuration options: sourceBasePath, targetBasePath
- [x] Method `output()` is completely missing

API page for [\Assets\Collection](http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Collection.html):

- [x] Method `setPrefix()` is missing

**Comment by ninjapanzer** [comment]
I think part of the problem here is the asset manager is not without bugs especially with joining and minification of css. So I think these issues need to be addressed together

**Comment by niden** [comment]
Closing in favor of https://github.com/phalcon/docs/issues/2322

**Comment by niden** [comment]
Addressed in b7da8dbd2f32192cb5687dd2d51efd43a7302ff6
