### ISSUE TITLE
Incomplete API docs

### ISSUE THREAD

**Issue by kolypto** [phalcon/docs#335]
After the 2.0 release, someone should compare the API docs with the source to resolve the following:

* Missing methods (see #334)
* Wrong descriptions (copy-pasted and not fixed)
* Wrong argument types & return types
* **The most annoying**: most classes do not document their options (also see #334). If some function accepts an array, the user needs to know an array of *what* is expected at the input.

**Comment by SidRoberts** [comment]
Fixed in 3d97b16 and 9edc555.
