### ISSUE TITLE
Wrong graph data in benchmark

### ISSUE THREAD

**Issue by rompcik** [phalcon/docs#347]
The data in the first two graphs of "Hello World Benchmark" differ from the shown benchmarks: While the benchmark for Yii shows 961.28 requests/s, the first graph shows only 851,83. The second graph shows a value of 1,174 ms/request for Yii, while the benchmark shows 1,040 ms/request, Data for other frameworks seem to be correct, but not for Yii.

**Comment by SidRoberts** [comment]
For future reference, the benchmark pages have since been removed (see 45c570ebfde95f99b7f0c248dbb180c28d5a0003).

**Comment by rompcik** [comment]
Thx. But it has taken a long time to remove that. It's better for you, since your framework must now compete with lumen and slim3, written in pure PHP5... And PHP7 will even minimize the difference.
