### ISSUE TITLE
Typo (Volt: Template Engine) Documentation

### ISSUE THREAD

**Issue by enajeeb** [phalcon/docs#357]
Missing closing % in Tests More examples. See screen shot.

http://phalcon-php-framework-documentation.readthedocs.org/en/latest/reference/volt.html#if

![screen shot 2014-03-07 at 9 19 01 am](https://f.cloud.github.com/assets/3844941/2359839/b277c504-a61c-11e3-8f83-aebc622abe35.png)

**Comment by andresgutierrez** [comment]
Fixed in master
