### ISSUE TITLE
incorrect sample code on "Assets Management" page

### ISSUE THREAD

**Issue by racztiborzoltan** [phalcon/docs#395]
http://docs.phalconphp.com/en/latest/reference/assets.html#minification-filtering

```
    ->addJs('code.jquery.com/jquery-1.10.0.min.js', true, false)
```

correctly:
```
    ->addJs('http://code.jquery.com/jquery-1.10.0.min.js', false, false)
```

Used Phalcon version: v1.3.1

**Comment by SidRoberts** [comment]
Fixed in 07c188c419763212ba0d5cc1e35df82ba68e1206 and 9e097e37a48a4c7c376cdeba0c38392f1f98d214.
