### ISSUE TITLE
Router default parameter value

### ISSUE THREAD

**Issue by aambrozkiewicz** [phalcon/docs#396]
Hi, defined a route like this:

$router->add('/{date}', [
    'controller' => 'index',
    'action' => 'index',
    'defaults' => [
        'date' => 'today'
    ]
]);

and var_dump in action seems to pick up it correctly but handle() method in front controller seem to have problem with it:

Warning: Illegal offset type in /Users/aleksander/php/kociouek/public/index.php on line 27
Call Stack
# Time    Memory  Function    Location

1   0.0002  239888  {main}( )   ../index.php:0
2   0.0010  270800  handle ( )  ../index.php:27
3   0.0012  276496  handle ( )  ../index.php:27

**Comment by niden** [comment]
Closing this because it is no longer relevant. The Router code has changed and the 4th parameter is expecting the position (first/last)
