### ISSUE TITLE
Has 'transifex.com' been deprecated? 

### ISSUE THREAD

**Issue by mr5** [phalcon/docs#402]
I has wrote some Chinese translation  to 'transifex.com' on  3 days ago, but it's still with 'UNREVIEWED' status. Has 'transifex.com' been deprecated ? whether I must push them to Github? My 'transifex.com' ID is 'mr5'.

**Comment by SidRoberts** [comment]
For anyone reading this in the future, Transifex is no longer in use (see #717 for details).
