### ISSUE TITLE
Issues with the micro version

### ISSUE THREAD

**Issue by AchrafSoltani** [phalcon/docs#405]
Hello,

There are some issues with the micro version :

This is the code snippet :

    //Return a rendered view
    $app->get('/products/show', function() use ($app) {
    
    // Render app/views/products/show.phtml passing some variables
    echo $app['view']->render('products/show', array(
            'id' => 100,
            'name' => 'Artichoke'
        ));

    });

with echo : PHP Catchable fatal error:  Object of class Phalcon\\Mvc\\View could not be converted to string

I tried to replace echo with "return" and I got this 

PHP Fatal error:  Call to undefined function Phalcon\\Mvc\\View::issent()

on 
    $app->handle();

**Comment by DevGator** [comment]
I know this has been open for awhile but this worked for me:

    public function actionName() {
      return $this->view->render('controllerName', 'actionName');
    }
It's not very well documented but you have to include both the controller and action name and in my case return instead of echo to get rid of the error.

**Comment by SidRoberts** [comment]
Fixed in 1381b41748b2c4df8d85c10415ec3ec3fec73095
