### ISSUE TITLE
Parameter of Phalcon\Http\Request::getJsonRawBody() is not documented

### ISSUE THREAD

**Issue by ryo-utsunomiya** [phalcon/docs#413]
Phalcon\Http\Request::getJsonRawBody() has parameter $assoc but this is not documented.

https://github.com/phalcon/cphalcon/blob/master/ext/http/request.c#L959
https://github.com/phalcon/docs/blob/master/en/api/Phalcon_Http_Request.rst

Is there any problem with doc comment or gen-api.php?

**Comment by SidRoberts** [comment]
Fixed in 0cda9aae466f6335dd16d03efcfbcc04daf4fb99.
