### ISSUE TITLE
Need to add file location to the examples

### ISSUE THREAD

**Issue by mhightower** [phalcon/docs#423]
Going through the REST app tutorial I could not determine which file the example code should be placed in, starting at http://docs.phalconphp.com/en/latest/reference/tutorial-rest.html#retrieving-data
we should place a comment in each example ie:
//app/models/Robots.php
or 
//public/index.php
or write in the instructions the following examples should be placed in this file.

**Comment by niden** [comment]
Fixed with : 62e816a2aa41b41aa6cfa8fd656c6c6f2e33a945
