### ISSUE TITLE
Suggestion of more clear explanation of Phalcon\Mvc\Url::get()

### ISSUE THREAD

**Issue by Conradaek** [phalcon/docs#432]
Current version of example code at http://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Url.html  is not enough.

I suggest to change it for: 

```php

<?php

//Generate a URL appending the URI to the base URI
echo $url->get('products/edit/1');

//Generate a URL for a predefined route
echo $url->get(array(
    'for' => 'blog-post',
    'title' => 'some-cool-stuff',
    'year' => '2012',
));

//generates e.g. /show/products?id=1&name=Carrots
echo $url->get('/show/products', array('id' => 1, 'name' => 'Carrots'));

```

Added 3rd example is taken from http://forum.phalconphp.com/discussion/627/phalcon-mvc-url-get-append-query-params-examples

Also the code provided by me should be modified in order to explain the last parameter of `get()` method. I mean 3rd argument which is `$locale`. 

I asked a question on Phosphorum here http://forum.phalconphp.com/discussion/3153/what-s-last-argument-in-phalcon-mvc-url-get-for- and I will update the proposed code when sb will answer me.

**Comment by SidRoberts** [comment]
I've added a PR to the main Phalcon repo. You can follow its status at https://github.com/phalcon/cphalcon/pull/11047.
