### ISSUE TITLE
Incorrect method name usage

### ISSUE THREAD

**Issue by adamdama** [phalcon/docs#442]
On this page:
http://phalcon-php-framework-documentation.readthedocs.org/en/latest/reference/db.html#altering-tables

At the bottom there is a reference to 'deleteColumn' method of the DB Adapter, however this method does not exist and should say 'dropColumn' instead.

This was really confusing for a while!

**Comment by SidRoberts** [comment]
Fixed in f8c54bc8886168c84eaa30a22b38ee9d9983d723.
