### ISSUE TITLE
Incomplete instruction for OS X homebrew installation

### ISSUE THREAD

**Issue by e-oz** [phalcon/docs#472]
http://docs.phalconphp.com/en/latest/reference/install.html 
![screenshot 2014-10-19 20 56 51](https://cloud.githubusercontent.com/assets/526352/4693884/ff9d0d4e-57b0-11e4-848a-4164a77455d5.png)

And the result is:

```
OZ$ brew tap homebrew/homebrew-php
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 7208, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 7208 (delta 8), reused 0 (delta 0)
Receiving objects: 100% (7208/7208), 1.45 MiB | 440.00 KiB/s, done.
Resolving deltas: 100% (4724/4724), done.
Checking connectivity... done.
Tapped 416 formulae
OZ-book:tmp OZ$ brew install php55-phalcon
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 1374, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1374 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1374/1374), 275.29 KiB | 276.00 KiB/s, done.
Resolving deltas: 100% (744/744), done.
Checking connectivity... done.
Tapped 36 formulae
Error: No available formula for zlib (dependency of php55-phalcon)
Please tap it and then try again: brew tap homebrew/dupes
Searching taps...
OZ-book:tmp OZ$ 
```

**Comment by luhuiya** [comment]
extension=/usr/local/opt/php55-phalcon/phalcon.so

this solved my problem

**Comment by mwinter343** [comment]
Hi, I'm having the same problem trying to install this on yosemite.  Where do you put this line in the php.ini file?  Does it matter where?

Thanks

**Comment by magroski** [comment]
"After using the homebrew method of installing phalcon on my Mac OS X Yosemite system this extension=/usr/local/opt/php55-phalcon/phalcon.so was all I needed to add to php.ini to get it working. Would've saved me some time if that had been included in the install instructions for Mac OS X on the phalcon site."

This!

**Comment by sergeyklay** [comment]
@SidRoberts Could you please take a look?

**Comment by HendrikEduard** [comment]
I added extension=/usr/local/opt/php71-phalcon/phalcon.so  to my php.ini file and still no Phalcon in phpinfo()...

Next idea??  Or should I just stay with my current MVC...
