### ISSUE TITLE
getJsonRawBody() return an stdClass

### ISSUE THREAD

**Issue by blckshrk** [phalcon/docs#481]
Hi,

According to the [documentation](http://docs.phalconphp.com/en/latest/api/Phalcon_Http_Request.html) `getJsonRawBody()`should return a `string`, but in my case it actually returns an  `Object`of`stdClass`.

I called the function in a controller in a Micro application.

Is the documentation outdated ?

Thanks

**Comment by andresgutierrez** [comment]
Fixed in master
