### ISSUE TITLE
No post with parameter example in the micro framework page.

### ISSUE THREAD

**Issue by faan11** [phalcon/docs#496]
I had some problem when i need to create a post request.
In this link, there is no example about that.
http://docs.phalconphp.com/en/latest/reference/micro.html#routes-with-parameters
The only way (that i found) is to use $app and take it from request.
Could you put it in the doc? 

 $app->post('/api', function() use ($app) {
    $post = $app->request->getPost();
    print_r($post);
  });

**Comment by andresgutierrez** [comment]
Fixed in master
