### ISSUE TITLE
How to update translated rst files?

### ISSUE THREAD

**Issue by kenjis** [phalcon/docs#497]
In this repository, it seems there is no way to update translated rst files using latest json files downloaded from transifex.

How do you do it?

**Comment by niden** [comment]
We use the transifex client to pull that data from the transifex repository. 

There is currently a minor technical issue we are dealing with. I believe it will be resolved within the next couple of weeks.

**Comment by SidRoberts** [comment]
For anyone reading this in the future, Transifex is no longer in use (see #717 for details).
