### ISSUE TITLE
Error in http://phalconphp.com/en/download

### ISSUE THREAD

**Issue by mbboni** [phalcon/docs#531]
Hi.

In the page at the url http://phalconphp.com/en/download I have found an error.

In order to use the apt-add-repository command, you need to install the software-properties-common package, rather than the python-software-properties as indicated.

So the right command is:

sudo apt-get install software-properties-common

Best regards

**Comment by niden** [comment]
Can you issue a Pull Request with the change please?

**Comment by andresgutierrez** [comment]
Fixed in master
