### ISSUE TITLE
Pagination of Documentation into chunks

### ISSUE THREAD

**Issue by maan81** [phalcon/docs#536]
It is difficult to navigate around the documentation as it being a single piece of block. I was looking for a neatly paged documentation, or perhaps sections hidden & shown when clicked on the specific topic.

I feel crumbersome to scroll through the huge page to find a specific topic. Is there a place where I could get the neatly paginated documentation ?

**Comment by ninjapanzer** [comment]
Great Idea!

Unfortunately, pagination creates its own issues with searching a category. I am planning a more consistent navigation to make it easier to jump to sub category topics. As well as hiding duplicate examples which often make the docs extra long.

**Comment by maan81** [comment]
As I expected, pagination might be more complicated.

But I assume, the topics are quite decently arranged in the current page. Adding a javascript function to hide the contents, with only the topics visible should not be difficult. Server-side [searching] should not have any issues as it is going to be a  purely javascript function.

And server-side pagination can be ignored.
