### ISSUE TITLE
How to get Parameters in view in phtml template

### ISSUE THREAD

**Issue by vinaysikarwar** [phalcon/docs#546]
Hi,

I have one query, but i did not find a way to solve that in google.

Can you help me in getting clear with my doubts.

_I am using phtml engine, I am adding a functionality of reset pasword, with swift mailer. Every thing works fine, but i am not getting a way how to get parameter value in my reset.phtml file._

Mail.php I am setting the template like
$parameters = array_merge(array(
            'publicUrl' => $this->config->application->publicUrl,
        ), $params);

```
    return $this->view->getRender('emailTemplates', $name, $parameters, function($view){
        $view->setRenderLevel(View::LEVEL_LAYOUT);
    });
    return $view->getContent();
```

Now I want to get the parameters in my reset.phtml file.
I have used this echo $this->view->publicUrl.

Thanks
Waiting for the reply

**Comment by niden** [comment]
I don't quite understand your code there but the idea is that you send the variables in the view and then you use them from it like so:

```
$this->view->publicUrl = $publicUrl;
```

and in your view:

```
echo $this->view->publicUrl
```

Please note that this is the documentation repo. You will get a much faster response if you try either our discord server or our forum.
