### ISSUE TITLE
Vökuró in Russian

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#645]
just gonna leave this here, in order to refer to this issue

**Comment by phalcon** [comment]
It's icelandic :D

**Comment by sergeyklay** [comment]
I meant t10n into Russian Vökuró-related docs :stuck_out_tongue:

**Comment by beliarh** [comment]
I'll translate it.

**Comment by sergeyklay** [comment]
Thanks

**Comment by beliarh** [comment]
Fixed in c978d5a
