### ISSUE TITLE
Dedicated Instance and Slash Error

### ISSUE THREAD

**Issue by tidytrax** [phalcon/docs#657]
**Dedicated Instance**

Inside location, not working.
root   $root_path;

**In all examples**

index.php?_url=/$1 ... Slash must be removed to rewrite routes work
must be index.php?_url=$1

 # otherwise rewrite it
        if (!-e $request_filename) {
            rewrite ^(.+)$ /index.php?_url=/$1 last;
            break;
        }

**Comment by SidRoberts** [comment]
Thanks, this is fixed in #658.
