### ISSUE TITLE
[doc][view] TemplateAfter vs TemplateBefore

### ISSUE THREAD

**Issue by f3l1x** [phalcon/docs#669]
Documentation says at https://phalcon-php-framework-documentation.readthedocs.org/en/latest/reference/views.html#using-templates

```php
$this->setTemplateAfter('common');
```

But in template the **common.phtml** is before.

```html
<!-- app/views/index.phtml -->
<!DOCTYPE html>
<html>
    <head>
        <title>Blog's title</title>
    </head>
    <body>

        <!-- app/views/layouts/common.phtml -->

        <ul class="menu">
            <li><a href="/">Home</a></li>
            <li><a href="/articles">Articles</a></li>
            <li><a href="/contact">Contact us</a></li>
        </ul>

        <div class="content">

            <!-- app/views/layouts/posts.phtml -->

            <h1>Blog Title</h1>

            <!-- app/views/posts/last.phtml -->

            <article>
                <h2>This is a title</h2>
                <p>This is the post content</p>
            </article>

            <article>
                <h2>This is another title</h2>
                <p>This is another post content</p>
            </article>

        </div>

    </body>
</html>
```

Is it correct?

**Comment by SidRoberts** [comment]
The before/after refers to the rendering order. `setTemplateBefore()` renders the template (layouts/common.phtml) before the main layout (in this case layouts/posts.phtml);  `setTemplateAfter()` renders the template after the main layout. Obviously, this will only make a difference if a layout is set. [I've updated the docs](https://github.com/phalcon/docs/commit/1ecffa7b821a841e48a2e01039e49669d6f544af) (it'll take a while before the website is updated). Is it clear enough or does it need more explanation? :smile:

**Comment by f3l1x** [comment]
@SidRoberts Much better. Thank you.
