### ISSUE TITLE
Fix installing instruction for Phalcon Developer Tools on Mac OS X: .profile is sometimes ignored

### ISSUE THREAD

**Issue by BlueShark** [phalcon/docs#68]
The instruction says to insert these two lines at the end of ~/.profile:

export PATH=$PATH:/Users/scott/phalcon-tools
export PTOOLSPATH=/Users/scott/phalcon-tools

Didn't work for me. 

Turns out if you have .bash_profile or .bash_login files, then your .profile will be ignored by bash.

I fixed it by inserting the two lines into ./bash_login

**Comment by SidRoberts** [comment]
@sergeyklay, Does https://github.com/phalcon/phalcon-devtools/blob/master/phalcon.sh work on Mac?

**Comment by sergeyklay** [comment]
@SidRoberts https://github.com/phalcon/phalcon-devtools/blob/3.0.x/phalcon.sh#L40-L43

On 3.0.x branch - yes

**Comment by SidRoberts** [comment]
Fixed in https://github.com/phalcon/docs/pull/874.
