### ISSUE TITLE
The description of key to the viewCache is not very precise.

### ISSUE THREAD

**Issue by aisuhua** [phalcon/docs#691]
The documents part of "Caching View Fragments". It says below:

> When we do not define a key to the cache, the component automatically creates one using an MD5 hash of **the name of the view** currently being rendered. [https://docs.phalconphp.com/en/latest/reference/views.html#caching-view-fragments](https://docs.phalconphp.com/en/latest/reference/views.html#caching-view-fragments)

I searching the phalcon source code and i found out this is not the name of view. It is **controller/view** eg.posts/show

For example, when i visiting the url `http://localhost/posts/show`, and i cache the view "posts/show". The generated key of cache is md5("posts/show") not md5("show").

So, I think that the document says the key is "the name of the view" not very precise. Except we talk the name of an action as "controller/action" not only "action".

Thank ! Sorry my bad english.

**Comment by SidRoberts** [comment]
Thanks, I've fixed it in 62e16daf926ec0fc2e4df02e13ba77809f7c4214.
