### ISSUE TITLE
Links in Chinese are broken

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#705]
https://github.com/phalcon/docs/blob/master/zh/reference/mvc.rst

![2015-10-09 23 53 29](https://cloud.githubusercontent.com/assets/1256298/10405373/1df47848-6ee1-11e5-8a6d-428d536b90cb.png)

**Comment by SidRoberts** [comment]
They look and work fine on the [live site](https://docs.phalconphp.com/zh/latest/reference/mvc.html). I don't think GitHub properly formats RST links ([try the English version of MVC, for example](https://github.com/phalcon/docs/blob/master/en/reference/mvc.rst)).

**Comment by sergeyklay** [comment]
Ok. Thanks
