### ISSUE TITLE
Missed benchmark page

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#706]
**En**
https://github.com/phalcon/docs/blob/master/en/reference/benchmark.rst - 404
https://docs.phalconphp.com/en/latest/reference/benchmark/hello-world.html - 404

**Comment by andresgutierrez** [comment]
It's outdated and it was removed from the docs

**Comment by sergeyklay** [comment]
@andresgutierrez I have just faced with some independent sites that link to these pages. IMHO removing these pages is not the best solution. At least we now have broken links.
