### ISSUE TITLE
Typo in sqlite documentation

### ISSUE THREAD

**Issue by jazztickets** [phalcon/docs#710]
The fetchOne example says "fecthOne" in the code.

https://docs.phalconphp.com/en/latest/api/Phalcon_Db_Adapter_Pdo_Sqlite.html

**Comment by SidRoberts** [comment]
Thanks, [it's been fixed in the repo](https://github.com/phalcon/docs/commit/14cccd2afdd224f520ef90c8326a6144aac18a39) but the website hasn't updated yet.
