### ISSUE TITLE
Encryption/Decryption reference says AES-256 is rijndael-256-cbc

### ISSUE THREAD

**Issue by verzola** [phalcon/docs#719]
I'm implementing a Rest API with Phalcon that encrypts credit card information to AES-256 and it is written in Phalcon Documentation: "By default, this component provides secure encryption using AES-256 (rijndael-256-cbc)."

I'm not a expert, but after reading some articles on the internet, I've found an article that says:
It says: "Rijndael-256 is not AES-256"
https://www.leaseweb.com/labs/2014/02/aes-php-mcrypt-key-padding/

**Comment by SidRoberts** [comment]
Fixed in https://github.com/phalcon/docs/commit/c97c99410fb02c54ff7e3837e661c1303d9feedb
