### ISSUE TITLE
Add missing file(s): api/Phalcon_Security_Random.rst

### ISSUE THREAD

**Issue by beliarh** [phalcon/docs#722]
In e2c3f01 was added information about `Security\Random` class. `:doc:` references to `<../api/Phalcon_Security_Random>`, but it doesn't exists:

```
WARNING: unknown document: ../api/Phalcon_Security_Random

**Comment by sergeyklay** [comment]
I've [introduced](https://github.com/phalcon/cphalcon/pull/10804) `Phalcon\Security\Random` in Phalcon 2.0.7

https://github.com/phalcon/cphalcon/blob/master/CHANGELOG.md

**Comment by SidRoberts** [comment]
I'm updating the API at the moment. It'll be committed in a few minutes. :)

**Comment by SidRoberts** [comment]
I've updated it now. How do you feel about deprecating the docs API (https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model.html) in favour of api.phalconphp.com (https://api.phalconphp.com/class/Phalcon/Mvc/Model.html)? It seems redundant to have two systems. The source code for api.phalconphp.com is available at https://github.com/phalcon/phalcon-api-reference.
