### ISSUE TITLE
Sphinx error in install.rst (en, pl): 'Uknown target name: "script"'

### ISSUE THREAD

**Issue by beliarh** [phalcon/docs#723]
en/reference/install.rst:23
```
If you don't know what DLL to download, use the following script_ to figure it out.
```
pl/reference/install.rst:23
```
Jeżeli nie wiesz którą bibliotekę pobrać, use the following script_ to figure it out.
```
External link `script_` is not defined.

**Comment by SidRoberts** [comment]
I've wondered about this for a while. I've decided just to remove them because I can't find any reference to that script anywhere else (e30e135da43ad35cf65515ccdc6a242dd08b4738).
