### ISSUE TITLE
Password example vulnerable to timing attack

### ISSUE THREAD

**Issue by oaass** [phalcon/docs#750]
Just thought I would point out that the example in the security chapter of the docs are vulnerable to timing attack.

Here (http://phalcontip.com/discussion/58/protect-log-in-against-timing-attacks) I have provided an example and the solution.

**Comment by sergeyklay** [comment]
Can you please do a PR at least in English?

**Comment by oaass** [comment]
@sergeyklay Will do

**Comment by SidRoberts** [comment]
Closed with #751
