### ISSUE TITLE
[Q]What is necessary in PR ?

### ISSUE THREAD

**Issue by Jurigag** [phalcon/docs#766]
What i need to add to documentation after implementing some new feature to phalcon ? I guess i need only to describe it in Reference ? Beacause if i will generate api with script it will update all files, not only mine which i want(so i guess you will do it after realase of next version of phalcon ?).

So only edits in reference for new feature is enough ?

**Comment by sergeyklay** [comment]
@SidRoberts

**Comment by SidRoberts** [comment]
Yes, only edit the reference folder.

**Comment by Jurigag** [comment]
Well im native language is polish, i guess there is no sense if i add some docs in polish, while rest is in english ?

**Comment by SidRoberts** [comment]
Please add any new documentation in English (and Polish) and someone else will translate it into other languages later.
