### ISSUE TITLE
Table name same as keyword

### ISSUE THREAD

**Issue by tuandao** [phalcon/docs#796]
Hello,

We have a problem that the table in DB named same as the keyword ORDER.
So the query cannot do straight away. Even we have tried to put '..' or "..." or [...], nothing working.
Could you help us sort it out?

Tuan

**Comment by sergeyklay** [comment]
This is no docs issue. See https://github.com/phalcon/cphalcon/issues/11253
And this is fixed in Phalcon 2.1.x branch. See https://github.com/phalcon/cphalcon/pull/11535

@SidRoberts
