### ISSUE TITLE
Does "Working With Models" need to be updated to use the latest Validation method?

### ISSUE THREAD

**Issue by dschissler** [phalcon/docs#815]
I'm looking at [Working With Models](https://docs.phalconphp.com/en/latest/reference/models.html) and it seems like it is still recommending the new validation method of Mvc validation.  Perhaps these should give examples in the new way.

**Comment by Jurigag** [comment]
Yea, there must be PR done and merged after 2.1.x released.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/docs/milestones/2.1.x
