### ISSUE TITLE
PhalconPHP v2.1 migration section.

### ISSUE THREAD

**Issue by sszdh** [phalcon/docs#831]
Hi guys,
I think it will be nice if we have a section in DOC about 2.x migration to cover breaking BS changes & etc.

Like `validation` , `crypt` and so on....

Thanks

**Comment by sergeyklay** [comment]
Hello @sszdh We are preparing an article on this

**Comment by SidRoberts** [comment]
See https://blog.phalconphp.com/post/phalcon-3-0-0-released
