### ISSUE TITLE
Is it changed Dispatching functionality in Phalcon PHP?

### ISSUE THREAD

**Issue by butamuh4o** [phalcon/docs#835]
I read something in Phalcon documentation about Dispatching ([view here] in controller (https://docs.phalconphp.com/en/latest/reference/dispatching.html#dispatch-loop-events)). I was used before "afterExecuteRoute", but just check documentation today about it... and i found something that bothers me (about parameters):

```
public function afterExecuteRoute(Event $event, Dispatcher $dispatcher)
{
    // Executed before every found action
}
```

This is exact part of code from documentation. But if i placed that in my code, i will get "Catchable fatal error" about:

> Argument 1 passed to Adapters\Controllers::afterExecuteRoute() must be an instance of Phalcon\Events\Event, instance of Phalcon\Mvc\Dispatcher is given

Before i always place $dispatcher at first (and only one) parameter... So... is documentation wrong? Or this will be the right way in next Phalcon version? Or... i am doing something wrong?

Thanks

**Comment by SidRoberts** [comment]
beforeExecuteRoute/afterExecuteRoute methods in controllers accept only the (Dispatcher) as a parameter. Methods in event listeners (separate classes) accept (Event, Dispatcher). I didn't realise there was a consistency until you brought it up. :p I'll update the documentation tomorrow to clarify this.
