### ISSUE TITLE
"Object" section of DI docs likes to dance

### ISSUE THREAD

**Issue by IMSoP** [phalcon/docs#855]
The "Objects" section of https://docs.phalconphp.com/en/latest/reference/di.html is currently picking up some animation CSS, causing it to "dance" unreadably around the screen.

This appears to be because the documentation generator gives it an HTML id of "#object", and something else in the CSS is also using that rather than generic ID and applying `animation: 1s ease-in-out 0s normal none infinite running animate;`

Possible fixes:
- change the heading in the RST source, which would presumably change the ID
- change the documentation template to generate less generic IDs (which would unfortunately break incoming anchor links)
- change the other use of `#object` in the CSS to a less generic ID

**Comment by tembem** [comment]
IMHO changing css is better than rst. Changing *.rst will break other language as well.

**Comment by SidRoberts** [comment]
Fixed in #856.
