### ISSUE TITLE
Need to alert about MongoDB new driver with php 7 on documentation

### ISSUE THREAD

**Issue by Surt** [phalcon/docs#861]
I run into the ODM not working due to the new php7 mongo driver as a fool. I think that it must be alerted on the documentation. Any project using Mongo ODM with phalcon will not work with the new phalcon 3.0 There is an incubator adapter but all the mongo code must be rewrited (new Bson type instead of arrays, no MongoId, no MongoDate, etc etc...) so it's a big refactor if you are making use of mongo.

It will be good to alert the users about this issue on the blog.

**Comment by niden** [comment]
Fixed in a147c1720953c9c2d830d45d2c51e1891563f465
