### ISSUE TITLE
maybe a mistake

### ISSUE THREAD

**Issue by akmumu** [phalcon/docs#876]
in `docs/zh/reference/models.rst`
The original should be like this
![qq20160921-0](https://cloud.githubusercontent.com/assets/3242526/18703975/b51ff31e-801a-11e6-9921-c1bedf930b36.jpg)
but now some thing is gone away like this
![qq20160921-1](https://cloud.githubusercontent.com/assets/3242526/18704029/dd2382cc-801a-11e6-9bd0-d1ffec7077d5.jpg)

**Comment by akmumu** [comment]
@SidRoberts It may be the wrong format

**Comment by SidRoberts** [comment]
I'll fix this in a few hours.

https://github.com/phalcon/docs/blame/master/zh/reference/models.rst#L315
https://github.com/phalcon/docs/commit/7c1f254b9fdc1856d604c73f2ab233ae6594624b

**Comment by akmumu** [comment]
strong && handsome O(∩_∩)O

**Comment by SidRoberts** [comment]
The main site takes a while to update. The latest version is available here: http://phalcon-php-framework-documentation.readthedocs.io/en/latest/reference/models.html

**Comment by SidRoberts** [comment]
The main site takes a while to update. :(

**Comment by akmumu** [comment]
4 days has gone，but ...

**Comment by SidRoberts** [comment]
You may have to wait until the next release.
