### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#879]
OK: https://docs.phalconphp.com/en/2.0.0/
404: https://docs.phalconphp.com/en/3.0.0/

**Comment by SidRoberts** [comment]
I've added the [3.0.0 branch](https://github.com/phalcon/docs/tree/3.0.0) but I think @andresgutierrez may need to update readthedocs and/or the website.

**Comment by andresgutierrez** [comment]
Fixed

**Comment by sergeyklay** [comment]
@SidRoberts How about merging current master to the 3.0.0 ?

**Comment by SidRoberts** [comment]
I'm planning to accept PRs on master and 3.0.0. Whenever a PR is merged, I'll rebase it into the other branch so they'll always be identical.

**Comment by sergeyklay** [comment]
Thanks
