### ISSUE TITLE
Move Wiki to the Docs project

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/docs#886]
I propose to :
- Move Phalcon Wiki pages to the Docs project in order that the community could maintain them up to date and translate them
- Remove not relevant or outdated Wiki pages

**Comment by SidRoberts** [comment]
I like this idea but everything on the wiki is massively out of date. I think we should just delete every wiki page and just link to the documentation.

**Comment by niden** [comment]
This has been done. A couple of pages still exist about static code analyzers and an example about dependent dropdowns.
