### ISSUE TITLE
Phalcon\Mvc\Model::validate() docs are not up to date

### ISSUE THREAD

**Issue by dercoder** [phalcon/docs#889]
Please take a look at:
https://github.com/phalcon/cphalcon/issues/12296

**Comment by SidRoberts** [comment]
Model validation was changed in 3.0.0. All of the code from the cphalcon issue uses 2.0.0 code and is now incompatible with Phalcon 3.

The model validation code was updated in 6b51849ccfd04dc404c78b420637f335301450b3 and is now on its own page: https://docs.phalconphp.com/en/latest/reference/model-validation.html

**Comment by dercoder** [comment]
Ok thx. But the docs https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model_Validator_Uniqueness.html 
are still wrong

**Comment by SidRoberts** [comment]
Ahh, those PHPDoc comments are wrong. :|

It's confusing but:

* Phalcon\Mvc\Model\Validator\* can only be used with Phalcon\Mvc\Collection
* Phalcon\Validation\Validator\* can only be used with Phalcon\Mvc\Model

I've fixed it in https://github.com/phalcon/cphalcon/pull/12298
