### ISSUE TITLE
Missing php extension requirements

### ISSUE THREAD

**Issue by ruudboon** [phalcon/docs#919]
I would like to reduce memory footprint of my project and wondering what php extension are required for a minimal working Phalcon project.
Could we add this to the docs?

**Comment by sergeyklay** [comment]
@ruudboon Could you please send a PR?

**Comment by ruudboon** [comment]
@sergeyklay I would love to, but don't know the requirements. I'm doing trial and error now. Can I find the dependencies somewhere in the code?

**Comment by sergeyklay** [comment]
Most dependencies is standard PHP-extensions. But okay just add the dependencies that you have found. In fact, we will be able to amend this at any time

**Comment by sergeyklay** [comment]
Most dependencies is standard PHP-extensions. Like pdo, json, mbstring, etc. But okay just add the dependencies that you have found. In fact, we will be able to amend this at any time

**Comment by ruudboon** [comment]
Ok will try to do it soon.

**Comment by sergeyklay** [comment]
@ruudboon :
* `curl`
* `openssl`
* `mbstring`
* `pdo_sqlite`
* `fileinfo`
* `gettext`
* `gd2`

**Comment by ruudboon** [comment]
Cool @sergeyklay I will add it to the spreadsheet I'm working on.
Is something like GD2 really necessary if you not doing any images?

**Comment by sergeyklay** [comment]
@ruudboon really not necessary if you do not use Image classes

**Comment by jellisii** [comment]
Need to add `yaml` if using queue.

**Comment by sergeyklay** [comment]
* `libpcre3-dev` (Debian/Ubuntu)
* `pcre-devel` (CentOS)
* `pcre` ()Mac OS

**Comment by niden** [comment]
Fix  972f9abd6fff8ad10dc3dd7e4e5972a5d9d898e5
