### ISSUE TITLE
API docs need to be refreshed from Phalcon Zephir code

### ISSUE THREAD

**Issue by dschissler** [phalcon/docs#923]
So the API docs are looking a bit crusty and and they should be updated from fresh Phalcon Zephir code.  I don't know the exact process but maybe @niden @sergeyklay has an idea?  It would be good to have this.  @Jurigag says that it was last done in September.  In particular by doing this we can remove all of the old `array()` PHP 5.3 array format examples.

**Comment by dschissler** [comment]
Also the website needs be updated again because I missed two `jquery` upgrades in different locales from this PR: https://github.com/phalcon/docs/pull/921

**Comment by Jurigag** [comment]
I think @SidRoberts is doing most of stuff for docs repo. And then niden need to pull changes.

**Comment by dschissler** [comment]
@SidRoberts Could you regenerate the API docs from `cphalcon`?

**Comment by SidRoberts** [comment]
Which API docs: https://docs.phalconphp.com/en/latest/api/ or https://api.phalconphp.com/ ?

**Comment by Jurigag** [comment]
I think @dschissler means first link, as you can see there there is everywhere `array()` though you changed it to `[]` in phalcon anywhere.

**Comment by niden** [comment]
Closing this - The API reference docs will be released with the new documentation
