### ISSUE TITLE
Phalcon\Cache\BackendInterface->save() lacks of result explanation

### ISSUE THREAD

**Issue by disharmonized** [phalcon/docs#933]
`Phalcon\Cache\BackendInterface->save()` method return `bool` value, but documentation lacks of explanation what `true` means and what `false` means. So, `true` - is it okay, value saved either attempt failed (like in c-style)?

**Comment by niden** [comment]
Fixed in: 20ba5861b328e6660f4a86ee739d4e1065f8a45c
