### ISSUE TITLE
html Bug

### ISSUE THREAD

**Issue by kideny** [phalcon/docs#937]
https://docs.phalconphp.com/zh/latest/reference/di.html

please visit this page， i can't fix this bug.

we  should edit

id="object"

to

id="class-instances"

。

please help me ,thanks !

**Comment by sergeyklay** [comment]
@kideny Could you please send a PR?

**Comment by kideny** [comment]
i can't find this html in this repo....

**Comment by sergeyklay** [comment]
https://github.com/phalcon/docs/tree/master/zh/_theme/phalcon

**Comment by kideny** [comment]
like this  ? 
https://github.com/phalcon/docs/pull/936

**Comment by kideny** [comment]
@dreamsxin 召唤大神来帮忙！

**Comment by dreamsxin** [comment]
你是要修改那个文字不断跳的文字么？
```html
<div class="section" id="object">
<h4>对象（Object）<a class="headerlink" href="#object" title="永久链接至标题">¶</a></h4>
<p>这种类型注册服务需要一个对象。实际上，这个服务不再需要初始化，因为它已经是一个对象，可以说，这是不是一个真正的依赖注入，但是如果你想强制总是返回相同的对象/值，使用这种方式还是有用的:</p>
<div class="highlight-php"><div class="highlight"><pre><span class="cp">&lt;?php</span>

<span class="k">use</span> <span class="nx">Phalcon\Http\Request</span><span class="p">;</span>

<span class="c1">// 返回 Phalcon\Http\Request(); 对象</span>
<span class="nv">$di</span><span class="o">-&gt;</span><span class="na">set</span><span class="p">(</span>
    <span class="s2">"request"</span><span class="p">,</span>
    <span class="k">new</span> <span class="nx">Request</span><span class="p">()</span>
<span class="p">);</span>
</pre></div>
</div>
</div>
```

**Comment by kideny** [comment]
是的，这个bug，好久了。。。一直没解决。。。

**Comment by dreamsxin** [comment]
```css
animation: animate 1s infinite ease-in-out;
```

**Comment by kideny** [comment]
我对比了英文版，
html代码里的id="object"，应该是id="class-instances"，CSS里有这个ID的样式。
不知道为什么，中文本里的id="class-instances" 被替换成了id="object"。

**Comment by kideny** [comment]
id="object"这个样式应该是在别的地方被调用了，不能去修改这个id的样式。
而是应该使用，英文版原来的id="class-instances"，就可以了。
bug的原因，我已经找到了。但是老大给我的那个url里，我不知道怎么改。。。

**Comment by dreamsxin** [comment]
你既然改成了 class-instances，重新生成，就不会有那个了啊

**Comment by kideny** [comment]
哦，我提交了PR，一直没动静。。。我不确定，这样改对不对。。。
https://github.com/phalcon/docs/pull/936

**Comment by dreamsxin** [comment]
你可以按照这个生成试试 
```shell
sudo apt-get install sphinx-common
# or
sudo apt install python-pip
git clone https://github.com/dreamsxin/sphinx.git
cd sphinx
pip install . -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

cd zh
make html
```

**Comment by kideny** [comment]
额，我电脑是win10，这命令BASH跑不起来吧。。。

**Comment by niden** [comment]
I will close this because it is no longer relevant. We have ported the documentation in markdown which will handle this much easier.

Thank you for the input @kideny  and @dreamsxin

**Comment by kideny** [comment]
@niden    I am sorry . the bug is fixed after the PR accpted.
