### ISSUE TITLE
Interface api docs is empty

### ISSUE THREAD

**Issue by Jurigag** [phalcon/docs#939]
All interfaces docs are empty, script is not generating them, just everywhere is `...`. For classes though it works fine. Shouldn't be there docs for interfaces too instead of `...`?

Actually for 2.0.0 it was working fine - https://docs.phalconphp.com/en/2.0.0/api/Phalcon_Annotations_AdapterInterface.html

**Comment by niden** [comment]
This has been fixed with the new version of the docs
