### ISSUE TITLE
URIs do not decode automatically as expected

### ISSUE THREAD

**Issue by jesseforrest** [phalcon/docs#943]
Regarding automatic URL decoding, I would like to request that the docs be updated to distinguish between the behavior of `Router::URI_SOURCE_GET_URL` and `Router::URI_SOURCE_SERVER_REQUEST_URI`.

This is in reference to:
https://github.com/phalcon/cphalcon/issues/12614

**Comment by niden** [comment]
Fixed in e652a319e16eb623e50a858c89fb6b5c4c7bfc9c
