### ISSUE TITLE
Footer items are white on a white background

### ISSUE THREAD

**Issue by zachleigh** [phalcon/docs#947]
Items in the footer are completely illegible because they use white text on a white background. I'd make a pull request to fix it, but it seems like they are not included in this repo and are being pulled from static.phalconphp.com/www/css/phalcon.min.css.

![snapshot](https://cloud.githubusercontent.com/assets/5616626/23602007/b093616a-0291-11e7-9342-915b6a19c1ea.png)  

EDIT:     
The real problem is that on many pages the background texture isn't being pulled in.
```
GET https://static.phalconphp.com/images/flat_v3/texture.png 404 ()
```
On pages where the texture works:
```
url(../images/flat_v3/texture.png)
```
On pages where it doesn't load, the leading two dots are missing in the css:
```
url(/images/flat_v3/texture.png)
```
In browser tools, adding the two dots loads the image fine.

**Comment by sergeyklay** [comment]
Cc: @niden

**Comment by niden** [comment]
@zachleigh Thank you.

It was a typo really that caused this. In all CSS we reference the `static` URL but somehow those entries did not change properly.

I made the change to our minified CSS and invalidated the cache on our CDN. The changes should propagate shortly which will correct this issue.
