### ISSUE TITLE
Suggestion - Version chooser

### ISSUE THREAD

**Issue by seliver** [phalcon/docs#959]
Hello! I have a suggestion to improve the documentation page.

**Use case**: Every time I visit the documentation page at https://docs.phalconphp.com/en/latest/index.html, I only can see the latest documentation available. 

**The problem**: I quite ofter need to read documentation of older versions, but there isn't a way (at least one I could easily find).

Is this possible? 

Thank you!

**Comment by Jurigag** [comment]
Instead of latest - 3.0.0, 2.0.0, not sure 1.3.x versions

**Comment by ninjapanzer** [comment]
I think this should coincide with #1173

**Comment by ninjapanzer** [comment]
@Jurigag We should maintain `latest` for semantic reasons when people are using external search engines but a drop-down or better yet something that displays health status along with the version number would be extra convenient.

**Comment by niden** [comment]
The `latest` should always be present but not "resolved". It should redirect to the latest version at the time. This way search engines will not query `latest` but `3.0`, `4.0` etc.

**Comment by niden** [comment]
I need to check the `latest` functionality that it redirects properly to the latest version. Once that is done this issue can be closed.

**Comment by niden** [comment]
The `latest` redirects to the latest version which for now is `3.4`
