### ISSUE TITLE
Stop accepting PRs to master

### ISSUE THREAD

**Issue by Jurigag** [phalcon/docs#966]
Like add branches to make repository like phalcon((3.1.x 3.2.x etc) so we don't by mistake release some new doc version with new feature documented in 3.1.x while actually it was implemented in 3.2.x etc

@niden @sergeyklay @SidRoberts what you think?

**Comment by sergeyklay** [comment]
Done

**Comment by Jurigag** [comment]
Also it could be nice to view docs of next minor version, like https://docs.phalconphp.com/en/latest will be still latest master branch(current phalcon docs), https://docs.phalconphp.com/en/3.1.x will be 3.1.x so upcoming docs for next bugfix version of phalcon and https://docs.phalconphp.com/en/3.2.x will be docs of next minor version.

Like update it too when releasing new bugfix version @niden
