### ISSUE TITLE
Not apparent in tutorial.rst that each view needs to be an index.html within a folder with the controller prefix

### ISSUE THREAD

**Issue by craigmdennis** [phalcon/docs#98]
https://github.com/phalcon/docs/blob/master/en/reference/tutorial.rst

The initial information about views indicates that the structure is `view/index.phtml` rather than what it should be `index/index.phtml` meaning when you come to add the signup view, you expect to use `views/signup.phtml` instead of what you should use `views/signup/index.phtml`. 

A simple sentence explaining this would have saved me half an hour or guessing.

**Comment by alec-w** [comment]
The current tutorial appears to clear this up. Can this be closed now?
